import { STEP_SYSTEM_FIELDS } from '../../../../../../../utils/SystemFieldsConstants';

export const STEP_SYETEM_FIELDS_MANIULATOR = [
  STEP_SYSTEM_FIELDS.ASSIGNED_ON,
  STEP_SYSTEM_FIELDS.ACCEPTED_BY,
  STEP_SYSTEM_FIELDS.ACCEPTED_ON,
  STEP_SYSTEM_FIELDS.COMPLETED_BY,
  STEP_SYSTEM_FIELDS.COMPLETED_ON,
  STEP_SYSTEM_FIELDS.BUTTON_ACTION,
  STEP_SYSTEM_FIELDS.COMMENTS,
  STEP_SYSTEM_FIELDS.DUE_DATE,
];
