/**
 * @author Asttle
 * @email asttlej@vuram.com
 * @create date 2019-11-27 20:34:35
 * @modify date 2019-11-27 20:34:35
 * @desc [description]
 */

const generateActionName = (parent, value) => parent.concat('_', value);
export const ACTION_CONSTANTS = {
  ADMIN_PROFILE_ACTION: 'ADMIN_PROFILE_ACTION',
  UPDATE_ADMIN_PROFILE_ACTION: 'UPDATE_ADMIN_PROFILE_ACTION',
  MEMBER_PROFILE_ACTION: 'MEMBER_PROFILE_ACTION',
  FLOW_CREATOR_PROFILE_ACTION: 'FLOW_CREATOR_PROFILE_ACTION',
  ROLE_ACTION: 'ROLE_ACTION',
  ROLE_ACTION_DOMAIN_NAME: 'ROLE_ACTION_DOMAIN_NAME',
  ROLE_ACTION_ACOUNT_LOCALE: 'ROLE_ACTION_ACOUNT_LOCALE',
  PRIMARY_LOCALE: 'PRIMARY_LOCALE',
  APP_HEADER_TYPE: 'APP_HEADER_TYPE',
  IS_SHOW_APP_TASKS: 'IS_SHOW_APP_TASKS',
  IS_COPILOT_ENABLED: 'IS_COPILOT_ENABLED',
  ENABLE_PROMPT: 'ENABLE_PROMPT',
  COLOR_CODE_ACTION: 'COLOR_CODE_ACTION',
  SET_ACCOUNT_COMPLETION_STATUS: 'SET_ACCOUNT_COMPLETION_STATUS',
  MANUAL_ACCOUNT_COMPLETION_STATUS: 'MANUAL_ACCOUNT_COMPLETION_STATUS',
  CLEAR_ACCOUNT_COMPLETION_STATUS: 'CLEAR_ACCOUNT_COMPLETION_STATUS',
  DATA_VALIDATION_FAILURE: 'DATA_VALIDATION_FAILURE',
  COUNTRY_LIST_SET: 'COUNTRY_LIST_SET',
  USER_LOGOUT_ACTION: 'USER_LOGOUT_ACTION',
  UPDATE_LOGO_ACTION: 'UPDATE_LOGO_ACTION',
  // UPDATE_USER_TYPE: 'UPDATE_USER_TYPE',
  FORM_POPOVER_STATUS_ACTION: 'FORM_POPOVER_STATUS_ACTION',
  EDIT_CONFIRM_POPOVER_STATUS_ACTION: 'EDIT_CONFIRM_POPOVER_STATUS_ACTION',
  CONFIRM_POPOVER_ACTION: 'CONFIRM_POPOVER_ACTION',
  CONFIRM_POPOVER_CLEAR: 'CONFIRM_POPOVER_CLEAR',
  POST_LOADER_ACTION: 'POST_LOADER_ACTION',
  UPDATE_LANGUAGE_ACTION: 'UPDATE_LANGUAGE_ACTION',
  UPDATE_ADMIN_PROFILE_PIC: 'UPDATE_ADMIN_PROFILE_PIC',
  UPDATE_MEMBER_PROFILE_PIC: 'UDATE_MEMBER_PROFILE_PIC',
  UPDATE_FLOW_CREATOR_PROFILE_PIC: 'UPDATE_FLOW_CREATOR_PROFILE_PIC',
  ALERT_POPOVER_STATUS_ACTION: 'ALERT_POPOVER_STATUS_ACTION',
  CLEAR_ALERT_POPOVER_STATUS_ACTION: 'CLEAR_ALERT_POPOVER_STATUS_ACTION',
  UPDATE_PIC_SIZE: 'UPDATE_PIC_SIZE',
  FORM_FEEDBACK_UPDATE: 'FORM_FEEDBACK_UPDATE',
  FORM_FEEDBACK_ADD: 'FORM_FEEDBACK_ADD',
  SET_IS_ACCOUNT_EXPIRED: 'SET_IS_ACCOUNT_EXPIRED',
  SET_EXPIRY_REMAINING: 'SET_EXPIRY_REMAINING',
  ALREADY_EXISTING_ACCOUNT: 'ALREADY_EXISTING_ACCOUNT',
  IS_BILLING_USER: 'IS_BILLING_USER',
  ACCOUNT_SUBSCRIPTION_TYPE: 'ACCOUNT_SUBSCRIPTION_TYPE',
  IS_ACCOUNT_CARD_VERIFIED: 'IS_ACCOUNT_CARD_VERIFIED',
  SET_TIMEZONE_LANGUAGE: 'SET_TIMEZONE_LANGUAGE',
  HAS_BILLING_PROFILE_COMPLETED: 'HAS_BILLING_PROFILE_COMPLETED',
  USAGE_DASHBOARD: 'USAGE_DASHBOARD',
};

export const SIGN_UP = {
  STARTED: 'SIGN_UP_STARTED',
  SUCCESS: 'SIGN_UP_SUCCESS',
  FAILURE: 'SIGN_UP_FAILURE',
  CANCEL: 'SIGN_UP_CANCEL',
  SET_STATE: 'SIGN_UP_SET_STATE',
  CLEAR: 'SIGN_UP_CLEAR',
};

export const SIGN_UP_BASIC_DETAILS = {
  STARTED: 'SIGN_UP_BASIC_DETAILS_STARTED',
  // SUCCESS: 'GENERATE_OTP_API_SUCCESS',
  // FAILURE: 'GENERATE_OTP_API_FAILURE',
  CANCEL: 'SIGN_UP_BASIC_DETAILS_CANCEL',
  SET_STATE: 'SIGN_UP_BASIC_DETAILS_SET_STATE',
  CLEAR: 'SIGN_UP_BASIC_DETAILS_CLEAR',
};

export const SIGN_UP_OTP_VERIFICATION = {
  STARTED: 'SIGN_UP_OTP_VERIFICATION_STARTED',
  SUCCESS: 'SIGN_UP_OTP_VERIFICATION_SUCCESS',
  // FAILURE: 'GENERATE_OTP_API_FAILURE',
  CANCEL: 'SIGN_UP_OTP_VERIFICATION_CANCEL',
  SET_STATE: 'SIGN_UP_OTP_VERIFICATION_SET_STATE',
  CLEAR: 'SIGN_UP_OTP_VERIFICATION_CLEAR',
};

export const MFA_OTP_VERIFICATION = {
  STARTED: 'MFA_OTP_VERIFICATION_STARTED',
  SUCCESS: 'MFA_OTP_VERIFICATION_SUCCESS',
  CANCEL: 'MFA_OTP_VERIFICATION_CANCEL',
  SET_STATE: 'MFA_OTP_VERIFICATION_SET_STATE',
  CLEAR: 'MFA_OTP_VERIFICATION_CLEAR',
};

export const SIGN_UP_ADDITIONAL_DETAILS = {
  STARTED: 'SIGN_UP_ADDITIONAL_DETAILS_STARTED',
  SUCCESS: 'SIGN_UP_ADDITIONAL_DETAILS_SUCCESS',
  // FAILURE: 'GENERATE_OTP_API_FAILURE',
  CANCEL: 'SIGN_UP_ADDITIONAL_DETAILS_CANCEL',
  SET_STATE: 'SIGN_UP_ADDITIONAL_DETAILS_SET_STATE',
  CLEAR: 'SIGN_UP_ADDITIONAL_DETAILS_CLEAR',
};

export const SIGN_IN_API = {
  STARTED: 'SIGN_IN_API_STARTED',
  SUCCESS: 'SIGN_IN_API_SUCCESS',
  FAILURE: 'SIGN_IN_API_FAILURE',
  CANCEL: 'SIGN_IN_API_CANCEL',
  SET_STATE: 'SIGN_IN_API_SET_STATE',
  CLEAR: 'SIGN_IN_API_CLEAR',
};

export const FORGOT_PASSWORD_API = {
  STARTED: 'FORGOT_PASSWORD_API_STARTED',
  SUCCESS: 'FORGOT_PASSWORD_API_SUCCESS',
  FAILURE: 'FORGOT_PASSWORD_API_FAILURE',
  CANCEL: 'FORGOT_PASSWORD_API_CANCEL',
  SET_STATE: 'FORGOT_PASSWORD_API_SET_STATE',
  CLEAR: 'FORGOT_PASSWORD_API_CLEAR',
};

export const RESET_PASSWORD = {
  STARTED: 'RESET_PASSWORD_STARTED',
  SUCCESS: 'RESET_PASSWORD_SUCCESS',
  FAILURE: 'RESET_PASSWORD_FAILURE',
  CANCEL: 'RESET_PASSWORD_CANCEL',
  SET_STATE: 'RESET_PASSWORD_SET_STATE',
};

export const USER_PROFILE = {
  STARTED: 'USER_PROFILE_STARTED',
  SUCCESS: 'USER_PROFILE_SUCCESS',
  FAILURE: 'USER_PROFILE_FAILURE',
  CANCEL: 'USER_PROFILE_CANCEL',
  SET_STATE: 'USER_PROFILE_SET_STATE',
};

export const CHANGE_PASSWORD = {
  STARTED: 'CHANGE_PASSWORD_STARTED',
  FAILURE: 'CHANGE_PASSWORD_FAILURE',
  CANCEL: 'CHANGE_PASSWORD_CANCEL',
  CLEAR: 'CHANGE_PASSWORD_CLEAR',
  SET_STATE: 'CHANGE_PASSWORD_SET_STATE',
};

export const CREATE_TASK = {
  // STARTED: 'CREATE_TASK_API_STARTED',
  // SUCCESS: 'CREATE_TASK_API_SUCCESS',
  // FAILURE: 'CREATE_TASK_API_FAILURE',
  CANCEL: 'CREATE_TASK_API_CANCEL',
  SET_STATE: 'CREATE_TASK_SET_STATE',
  CLEAR: 'CREATE_TASK_CLEAR',
  SET_FORM_VISIBILITY: 'SET_FORM_VISIBILITY',
  ASSIGNEE_SUGGESTION_API_STARTED: 'ASSIGNEE_SUGGESTION_API_STARTED',
  SAVE_RULE: 'CREATE_TASK_SAVE_RULE',
  SET_FIELD_VALUE: 'CREATE_TASK_SET_FIELD_VALUE',
  SET_DATA_LIST_FIELD: 'CREATE_TASK_SET_DATA_LIST_FIELD',
  OPEN_FIELD_CONFIG: 'CREATE_TASK_OPEN_FIELD_CONFIG',
  SET_ENTIRE_FIELD: 'CREATE_TASK_SET_ENTIRE_FIELD',
  SET_FIELD_LIST_VALUE: 'CREATE_TASK_SET_FIELD_LIST_VALUE',
  SET_FIELD_LIST_VALIDATION: 'CREATE_TASK_SET_FIELD_LIST_VALIDATION',
  SET_DEFAULT_RULE_VALUE: 'CREATE_TASK_DEFAULT_RULE_VALUE',
  SET_SECTION_VALUE: 'CREATE_TASK_SET_SECTION_VALUE',
  SET_ERROR_LIST: 'CREATE_TASK_SET_ERROR_LIST',
  SET_ADDITIONAL_ERROR_LIST: 'CREATE_TASK_SET_ADDITIONAL_ERROR_LIST',
  FIELD_VISIBILITY_SAVE_RULE: 'FIELD_VISIBILITY_SAVE_RULE',
  SET_CREATE_TASK_VISIBILITY_FIELD_DATA:
    'SET_CREATE_TASK_VISIBILITY_FIELD_DATA',
  SET_REFERENCE_ID_LOADING: 'SET_REFERENCE_ID_LOADING',
  SET_AUTO_TRIGGER_DETAILS: 'SET_AUTO_TRIGGER_DETAILS',
  SET_TASK_REFERENCE_DOCUMENTS: 'SET_TASK_REFERENCE_DOCUMENTS',
};

export const LOOKUP = {
  ADD_LOOKUP_STATE_CHANGE: 'ADD_LOOKUP_STATE_CHANGE',
  CLEAR_LOOKUP: 'LOOKUP_CLEAR',
  ADD_NEW_LOOKUP_STARTED: 'ADD_NEW_LOOKUP_STARTED',
  ADD_NEW_LOOKUP_SUCCESS: 'ADD_NEW_LOOKUP_SUCCESS',
  ADD_NEW_LOOKUP_FAILURE: 'ADD_NEW_LOOKUP_FAILURE',
  TOGGLE_ADD_LOOKUP_MODAL_VISIBILITY: 'TOGGLE_ADD_LOOKUP_MODAL_VISIBILITY',
};

export const NOTIFICATIONS = {
  TOGGLE_NOTIFICATIONS_MODAL_VISIBILITY: 'TOGGLE_NOTIFICATION_MODAL_VISIBILITY',
  NOTIFIACTIONS_DATA_CHANGE: 'NOTIFIACTIONS_DATA_CHANGE',
  GET_ALL_NOTIFICATIONS_STARTED: 'GET_ALL_NOTIFICATIONS_STARTED',
  GET_ALL_NOTIFICATIONS_SUCCESS: 'GET_ALL_NOTIFICATIONS_SUCCESS',
  GET_ALL_NOTIFICATIONS_FAILURE: 'GET_ALL_NOTIFICATIONS_FAILURE',
  LOAD_MORE_NOTIFICATIONS_STARTED: 'LOAD_MORE_NOTIFICATIONS_STARTED',
  READ_NOTIFICATION_STARTED: 'READ_NOTIFICATION_STARTED',
  READ_NOTIFICATION_SUCCESS: 'READ_NOTIFICATION_SUCCESS',
  READ_NOTIFICATION_FAILURE: 'READ_NOTIFICATION_FAILURE',
  CLEAR_NOTIFICAIONS_STATE: 'CLEAR_NOTIFICAIONS_STATE',
};

export const BULK_UPLOAD = {
  BULK_UPLOAD_STARTED: 'BULK_UPLOAD_STARTED',
  BULK_UPLOAD_COMPLETED: 'BULK_UPLOAD_COMPLETED',
  BULK_UPLOAD_FAILURE: 'BULK_UPLOAD_FAILURE',
  BULK_DATA_LIST_ENTRY_CHANGE: 'BULK_DATA_LIST_ENTRY_CHANGE',
  BULK_DATA_LIST_ENTRY_ROW_DELETE: 'BULK_DATA_LIST_ENTRY_ROW_DELETE',
  BULK_DATA_LIST_ENTRY_VALIDATION_CHANGE:
    'BULK_DATA_LIST_ENTRY_VALIDATION_CHANGE',
  BULK_DATA_LIST_ENTRY_VALIDATION: 'BULK_DATA_LIST_ENTRY_VALIDATION',
};

export const DATA_LIST = {
  GET_ALL_DATA_LIST_API_STARTED: 'GET_ALL_DATA_LIST_API_STARTED',
  GET_ALL_RECENT_DATA_LIST_API_STARTED: 'GET_ALL_RECENT_DATA_LIST_API_STARTED',
  GET_ALL_OTHER_DATA_LIST_API_STARTED: 'GET_ALL_OTHER_DATA_LIST_API_STARTED',
  GET_ALL_INFINITE_SCROLL_OTHER_DATA_LIST_API_STARTED:
    'GET_ALL_INFINITE_SCROLL_OTHER_DATA_LIST_API_STARTED',
  GET_ALL_RECENT_DATA_LIST_API_FAILED: 'GET_ALL_RECENT_DATA_LIST_API_FAILED',
  GET_ALL_OTHER_DATA_LIST_API_FAILED: 'GET_ALL_OTHER_DATA_LIST_API_FAILED',
  CLEAR_LANDING_PAGE_DATA_LIST: 'CLEAR_LANDING_PAGE_DATA_LIST',
  GET_ALL_RECENT_DATA_LIST_API_SUCCESS: 'GET_ALL_RECENT_DATA_LIST_API_SUCCESS',
  GET_ALL_OTHERS_DATA_LIST_API_SUCCESS: 'GET_ALL_OTHERS_DATA_LIST_API_SUCCESS',
  GET_ALL_DATA_LIST_API_FAILED: 'GET_ALL_DATA_LIST_API_FAILED',
  GET_DATA_LIST_BY_DETAILS_STARTED: 'GET_DATA_LIST_BY_DETAILS_STARTED',
  GET_DATA_LIST_BY_DETAILS_SUCCESS: 'GET_DATA_LIST_BY_DETAILS_SUCCESS',
  GET_DATA_LIST_BY_DETAILS_FAILED: 'GET_DATA_LIST_BY_DETAILS_FAILED',
  GET_ALL_DATA_LIST_ENTRIES_STARTED: 'GET_ALL_DATA_LIST_ENTRIES_STARTED',
  GET_ALL_DATA_LIST_LISTING_ENTRIES_SUCCESS:
    'GET_ALL_DATA_LIST_LISTING_ENTRIES_SUCCESS',
  GET_ALL_DATA_LIST_ENTRIES_FAILED: 'GET_ALL_DATA_LIST_ENTRIES_FAILED',
  GET_DATA_LIST_ENTRY_DETAILS_STARTED: 'GET_DATA_LIST_ENTRY_DETAILS_STARTED',
  GET_DATA_LIST_ENTRY_DETAILS_SUCCESS: 'GET_DATA_LIST_ENTRY_DETAILS_SUCCESS',
  GET_DATA_LIST_ENTRY_DETAILS_FAILED: 'GET_DATA_LIST_ENTRY_DETAILS_FAILED',
  ADD_DATA_LIST_DATA_UPDATE: 'ADD_DATA_LIST_DATA_UPDATE',
  UPDATE_ACTIVE_ENTRY_DETAILS: 'UPDATE_ACTIVE_ENTRY_DETAILS',
  ADD_NEW_NOTE_STARTED: 'ADD_NEW_NOTE_STARTED',
  ADD_NEW_NOTE_SUCCESS: 'ADD_NEW_NOTE_SUCCESS',
  ADD_NEW_NOTE_FAILURE: 'ADD_NEW_NOTE_FAILURE',
  SUBMIT_DATA_LIST_ENTRY_STARTED: 'SUBMIT_DATA_LIST_ENTRY_STARTED',
  SUBMIT_DATA_LIST_ENTRY_SUCCESS: 'SUBMIT_DATA_LIST_ENTRY_SUCCESS',
  SUBMIT_DATA_LIST_ENTRY_FAILED: 'SUBMIT_DATA_LIST_ENTRY_FAILED',
  DELETE_DATA_LIST_ENTRY_STARTED: 'DELETE_DATA_LIST_ENTRY_STARTED',
  DELETE_DATA_LIST_ENTRY_SUCCESS: 'DELETE_DATA_LIST_ENTRY_SUCCESS',
  DELETE_DATA_LIST_ENTRY_FAILURE: 'DELETE_DATA_LIST_ENTRY_FAILURE',
  TOGGLE_ADD_NEW_DATA_LIST_MODAL_VISIBILITY:
    'TOGGLE_ADD_NEW_DATA_LIST_MODAL_VISIBILITY',
  SET_DATA_LIST_ENTRY_POPUP_VISIBILITY: 'SET_DATA_LIST_ENTRY_POPUP_VISIBILITY',
  SET_VIEW_DATA_LIST_TAB_INDEX: 'SET_VIEW_DATA_LIST_TAB_INDEX',
  SET_DATA_LIST_DASHBOARD_VIEW_TYPE: 'SET_DATA_LIST_DASHBOARD_VIEW_TYPE',
  SET_DATA_LIST_DASHBOARD_TAB_INDEX: 'SET_DATA_LIST_DASHBOARD_TAB_INDEX',
  DATA_LIST_ENTRIES_LIST_PAGE_UPDATE: 'DATA_LIST_ENTRIES_LIST_PAGE_UPDATE',
  DATA_LIST_ENTRIES_LIST_TOTAL_COUNT_UPDATE:
    'DATA_LIST_ENTRIES_LIST_TOTAL_COUNT_UPDATE',
  UPDATE_SELECTED_DATA_LIST_ID: 'UPDATE_SELECTED_DATA_LIST_ID',
  UPDATE_SEARCH_TEXT_DATA_LIST: 'UPDATE_SEARCH_TEXT_DATA_LIST',
  UPDATE_FIELD_ON_VISIBILITY_CHANGE: 'UPDATE_FIELD_ON_VISIBILITY_CHANGE',
  ADD_NOTE_STATE_CHANGE: 'ADD_NOTE_STATE_CHANGE',
  DATA_LIST_STATE_CHANGE: 'DATA_LIST_STATE_CHANGE',
  DATA_LIST_DASHBOARD_PAGINATION_DATA: 'DATA_LIST_DASHBOARD_PAGINATION_DATA',
  DATA_LIST_SET_FILTER_FIELD_PARAMS: 'DATA_LIST_SET_FILTER_FIELD_PARAMS',
  DATA_LIST_SET_CHART: 'DATA_LIST_SET_CHART',
  DATA_LIST_CLEAR_CHART: 'DATA_LIST_CLEAR_CHART',
  DATA_LIST_SET_SAVED_SEARCH: 'DATA_LIST_SET_SAVED_SEARCH',
  DATA_LIST_CLEAR_SAVED_SEARCH: 'DATA_LIST_CLEAR_SAVED_SEARCH',
  DATA_LIST_SET_SEARCH: 'DATA_LIST_SET_SEARCH',
  DATA_LIST_CLEAR_SEARCH: 'DATA_LIST_CLEAR_SEARCH',
  DATA_LIST_DASHBOARD_SET_FILTER: 'DATA_LIST_DASHBOARD_SET_FILTER',
  DATA_LIST_REPORT_ENGINE_LOADING: 'DATA_LIST_REPORT_ENGINE_LOADING',
  DATA_LIST_FILTER_DIMENSION_LOADING: 'DATA_LIST_FILTER_DIMENSION_LOADING',
  DATA_LIST_REPORT_ENGINE_FAILURE: 'DATA_LIST_REPORT_ENGINE_FAILURE',
  GET_DATA_LIST_ENTRY_TASK_DETAILS_STARTED:
    'GET_DATA_LIST_ENTRY_TASK_DETAILS_STARTED',
  GET_DATA_LIST_ENTRY_TASK_DETAILS_SUCCESS:
    'GET_DATA_LIST_ENTRY_TASK_DETAILS_SUCCESS',
  GET_DATA_LIST_ENTRY_TASK_DETAILS_FAILED:
    'GET_DATA_LIST_ENTRY_TASK_DETAILS_FAILED',
  DATA_LIST_ENTRY_TASK_PAGE_CHANGE_ACTION:
    'DATA_LIST_ENTRY_TASK_PAGE_CHANGE_ACTION',
  DATA_LIST_ENTRY_TASK_ON_SEARCH: 'DATA_LIST.DATA_LIST_ENTRY_TASK_ON_SEARCH',
  DATA_LIST_ENTRY_TASK_ON_SEARCH_CLEAR:
    'DATA_LIST.DATA_LIST_ENTRY_TASK_ON_SEARCH_CLEAR',
  DATA_LIST_ENTRY_TASK_ON_SELECT: 'DATA_LIST.DATA_LIST_ENTRY_TASK_ON_SELECT',
  DATA_LIST_ENTRY_TASK_ROW_COUNT: 'DATA_LIST.DATA_LIST_ENTRY_TASK_ROW_COUNT',
  DATA_LIST_SET_INSTANCE_IDENTIFIER: 'DATA_LIST_SET_INSTANCE_IDENTIFIER',
  CLEAR_DATA_LIST: 'DATA_LIST_CLEAR',
  CLEAR_ADD_DATA_LIST_FORM_DATA: 'CLEAR_ADD_DATA_LIST_FORM_DATA',
  UPDATE_FILE_UPLOAD_PROGRESS: 'UPDATE_FILE_UPLOAD_PROGRESS',
  CLEAR_REFERENCE_ID: 'CLEAR_REFERENCE_ID',
  REVERT_TO_PREVIOUS_SEARCH: 'REVERT_TO_PREVIOUS_SEARCH',
  DATA_CHANGE: 'DATA_LIST_DASHBOARD_DATA_CHANGE',
  SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
  DATA_LIST_AUDIT_DATA_STARTED: 'DATA_LIST_AUDIT_DATA_STARTED',
  DATA_LIST_AUDIT_DATA_SUCESS: 'DATA_LIST_AUDIT_DATA_SUCESS',
  DATA_LIST_AUDIT_DATA_FAILED: 'DATA_LIST_AUDIT_DATA_FAILED',
  DATA_LIST_DATA_CHANGE: 'DATA_LIST_DATA_CHANGE',
  POPUP_TRUNCATE_VISIBLE: 'POPUP_TRUNCATE_VISIBLE',
  SET_DATA_LIST_MODEL_VISIBLE_FALSE: 'SET_DATA_LIST_MODEL_VISIBLE_FALSE',
};

export const CREATE_DATA_LIST = {
  DATA_LIST_STATE_CHANGE: 'CREATE_DATA_LIST_STATE_CHANGE',
  UPDATE_POLICY_CONDITION: 'UPDATE_POLICY_CONDITION',
  DATA_LIST_VALUES_STATE_CHANGE: 'DATA_LIST_VALUES_STATE_CHANGE',
  CLEAR: 'DATA_LIST_STATE_CLEAR',
  TOTAL_UPDATE: 'TOTAL_UPDATE',
  SAVE_DATA_LIST_STARTED: 'SAVE_DATA_LIST_STARTED',
  SAVE_DATA_LIST_SUCCESS: 'SAVE_DATA_LIST_SUCCESS',
  SAVE_DATA_LIST_FAILURE: 'SAVE_DATA_LIST_FAILURE',
  GET_ALL_FIELDS_DATA_LIST_STARTED: 'GET_ALL_FIELDS_DATA_LIST_STARTED',
  GET_ALL_FIELDS_DATA_LIST_SUCCESS: 'GET_ALL_FIELDS_DATA_LIST_SUCCESS',
  GET_ALL_FIELDS_DATA_LIST_FAILED: 'GET_ALL_FIELDS_DATA_LIST_FAILED',
  GET_ALL_OPERATORS_DATA_LIST_STARTED: 'GET_ALL_OPERATORS_DATA_LIST_STARTED',
  GET_ALL_OPERATORS_DATA_LIST_SUCCESS: 'GET_ALL_OPERATORS_DATA_LIST_SUCCESS',
  GET_ALL_OPERATORS_DATA_LIST_FAILED: 'GET_ALL_OPERATORS_DATA_LIST_FAILED',
  DATA_LIST_INITIAL_LOADING: 'DATA_LIST_INITIAL_LOADING',
  DATA_LIST_FORM_LOADING: 'DATA_LIST_FORM_LOADING',
  SET_SECTION_VALUE: 'CREATE_DATA_LIST_SET_SECTION_VALUE',
  SET_STATE: 'CREATE_DATA_LIST_SET_STATE',
  OPEN_FIELD_CONFIG: 'CREATE_DATA_LIST_OPEN_FIELD_CONFIG',
  SET_FIELD_VALUE: 'CREATE_DATA_LIST_SET_FIELD_VALUE',
  SET_FIELD_LIST_VALUE: 'CREATE_DATA_LIST_SET_FIELD_LIST_VALUE',
  SET_FIELD_LIST_VALIDATION: 'CREATE_DATA_LIST_SET_FIELD_LIST_VALIDATION',
  SET_ENTIRE_FIELD: 'CREATE_DATA_LIST_SET_ENTIRE_FIELD',
  SET_DEFAULT_RULE_VALUE: 'CREATE_DATA_LIST_SET_DEFAULT_RULE_VALUE',
  SET_VISIBILITY_FIELD_DATA: 'CREATE_DATA_LIST_SET_VISIBILITY_FIELD_DATA',
  SET_ERROR_LIST: 'CREATE_DATA_LIST_SET_ERROR_LIST',
  SAVE_RULE: 'CREATE_DATA_LIST_SAVE_RULE',
  CREATE_DATALIST_CHANGE: 'CREATE_DATALIST_CHANGE',
  IS_EDIT_DL: 'IS_EDIT_DL',
};

export const IMPORT_FORM = {
  IMPORT_TASK_FORM_STARTED: 'IMPORT_TASK_FORM_STARTED',
  IMPORT_TASK_FORM_SUCCESS: 'IMPORT_TASK_FORM_SUCCESS',
  IMPORT_TASK_FORM_FAILURE: 'IMPORT_TASK_FORM_FAILURE',
  IMPORT_TASK_FORM_DATA_CHANGE: 'IMPORT_TASK_FORM_DATA_CHANGE',
  IMPORT_TASK_FORM_SET_SECTION: 'IMPORT_TASK_FORM_SET_SECTION',
  IMPORT_TASK_FORM_SET_ENTIRE_SECTION: 'IMPORT_TASK_FORM_SET_ENTIRE_SECTION',
  IMPORT_TASK_FORM_SET_FIELD_LIST: 'IMPORT_TASK_FORM_SET_FIELD_LIST',
  IMPORT_TASK_FORM_SET_ENTIRE_FIELD_LIST:
    'IMPORT_TASK_FORM_SET_ENTIRE_FIELD_LIST',
  IMPORT_TASK_FORM_SET_FIELD: 'IMPORT_TASK_FORM_SET_FIELD',
  IMPORT_TASK_FORM_SET_ENTIRE_FIELD: 'IMPORT_TASK_FORM_SET_ENTIRE_FIELD',
  IMPORT_TASK_CLEAR_STATE: 'IMPORT_TASK_CLEAR_STATE',
  IMPORT_FORM_SET_SECTION_INDEX: 'IMPORT_FORM_SET_SECTION_INDEX',
  IMPORT_FORM_CANCEL: 'IMPORT_FORM_CANCEL',
};

export const CREATE_FLOW = {
  TAB_INDEX_CHANGE: 'CREATE_FLOW_TAB_INDEX_CHANGE',
  FLOW_DATA_CHANGE: 'FLOW_DATA_CHANGE',
  FLOW_SET_STEP: 'FLOW_SET_STEP',
  FLOW_SET_SECTION: 'FLOW_SET_SECTION',
  FLOW_SET_FIELD: 'FLOW_SET_FIELD',
  FLOW_OPEN_CONFIG: 'CREATE_FLOW_OPEN_CONFIG',
  FLOW_SET_ENTIRE_FIELD: 'FLOW_SET_ENTIRE_FIELD',
  FLOW_SET_FIELD_LIST: 'FLOW_SET_FIELD_LIST',
  FLOW_SET_FIELD_LIST_VALIDATION: 'FLOW_SET_FIELD_LIST_VALIDATION',
  FLOW_SET_ERROR_LIST: 'FLOW_SET_ERROR_LIST',
  FLOW_DEFAULT_RULE_VALUE: 'CREATE_FLOW_DEFAULT_RULE_VALUE',
  CREATE_FLOW_DATA_CHANGE: 'CREATE_FLOW_DATA_CHANGE',
  SET_DATA_INSIDE_FLOW_DATA: 'SET_DATA_INSIDE_FLOW_DATA',
  SUGGESION_ID_CHANGE: 'SUGGESION_ID_CHANGE',
  SAVE_FLOW_STARTED: 'SAVE_FLOW_STARTED',
  SAVE_FLOW_SUCCESS: 'SAVE_FLOW_SUCCESS',
  SAVE_FLOW_FAILURE: 'SAVE_FLOW_FAILURE',
  DETAILED_ERROR_INFO: 'DETAILED_ERROR_INFO',
  SAVE_STEP_STARTED: 'SAVE_STEP_STARTED',
  SAVE_STEP_SUCCESS: 'SAVE_STEP_SUCCESS',
  SAVE_STEP_FAILURE: 'SAVE_STEP_FAILURE',
  SAVE_FORM_STARTED: 'SAVE_FORM_STARTED',
  SAVE_FORM_SUCCESS: 'SAVE_FORM_SUCCESS',
  SAVE_FORM_FAILURE: 'SAVE_FORM_FAILURE',
  GET_ALL_STEPS_STARTED: 'GET_ALL_STEPS_STARTED',
  GET_FORM_DETAILS_STARTED: 'GET_FORM_DETAILS_STARTED',
  ACTION_NEW_STEP_NAME: 'ACTION_NEW_STEP_NAME',
  GET_ALL_STEPS_SUCCESS: 'GET_ALL_STEPS_SUCCESS',
  GET_ALL_STEPS_FAILURE: 'GET_ALL_STEPS_FAILURE',
  GET_FLOW_SUCCESS: 'GET_FLOW_SUCCESS',
  PUBLISH_FLOW_STARTED: 'PUBLISH_FLOW_STARTED',
  PUBLISH_FLOW_SUCCESS: 'PUBLISH_FLOW_SUCCESS',
  PUBLISH_FLOW_FAILURE: 'PUBLISH_FLOW_FAILURE',
  FIRST_FORM_DETAILS_STARTED: 'FIRST_FORM_DETAILS_STARTED',
  FIRST_FORM_DETAILS_SUCCESS: 'FIRST_FORM_DETAILS_SUCCESS',
  FIRST_FORM_DETAILS_FAILURE: 'FIRST_FORM_DETAILS_FAILURE',
  FIRST_FORM_DETAILS_CHANGE: 'FIRST_FORM_DETAILS_CHANGE',
  FIRST_FORM_DETAILS_SET_SECTION: 'FIRST_FORM_DETAILS_SET_SECTION',
  FIRST_FORM_DETAILS_SET_ENTIRE_SECTION:
    'FIRST_FORM_DETAILS_SET_ENTIRE_SECTION',
  FIRST_FORM_DETAILS_SET_FIELD_LIST: 'FIRST_FORM_DETAILS_SET_FIELD_LIST',
  FIRST_FORM_DETAILS_SET_ENTIRE_FIELD_LIST:
    'FIRST_FORM_DETAILS_SET_ENTIRE_FIELD_LIST',
  FIRST_FORM_DETAILS_SET_FIELD: 'FIRST_FORM_DETAILS_SET_FIELD',
  FIRST_FORM_DETAILS_SET_ENTIRE_FIELD: 'FIRST_FORM_DETAILS_SET_ENTIRE_FIELD',
  CLEAR_ACTION_DATA: 'CREATE_FLOW_CLEAR_ACTION_DATA',

  // import task form action constants
  IMPORT_TASK_FORM_STARTED: 'IMPORT_TASK_FORM_STARTED',
  IMPORT_TASK_FORM_SUCCESS: 'IMPORT_TASK_FORM_SUCCESS',
  IMPORT_TASK_FORM_FAILURE: 'IMPORT_TASK_FORM_FAILURE',
  IMPORT_TASK_FORM_CHANGE: 'IMPORT_TASK_FORM_CHANGE',
  IMPORT_TASK_FORM_SET_SECTION: 'IMPORT_TASK_FORM_SET_SECTION',
  IMPORT_TASK_FORM_SET_ENTIRE_SECTION: 'IMPORT_TASK_FORM_SET_ENTIRE_SECTION',
  IMPORT_TASK_FORM_SET_FIELD_LIST: 'IMPORT_TASK_FORM_SET_FIELD_LIST',
  IMPORT_TASK_FORM_SET_ENTIRE_FIELD_LIST:
    'IMPORT_TASK_FORM_SET_ENTIRE_FIELD_LIST',
  IMPORT_TASK_FORM_SET_FIELD: 'IMPORT_TASK_FORM_SET_FIELD',
  IMPORT_TASK_FORM_SET_ENTIRE_FIELD: 'IMPORT_TASK_FORM_SET_ENTIRE_FIELD',

  ALL_FIELDS_STARTED: 'ALL_FIELDS_STARTED',
  ALL_FIELDS_SUCCESS: 'ALL_FIELDS_SUCCESS',
  ALL_TABLE_FIELDS_SUCCESS: 'ALL_TABLE_FIELDS_SUCCESS',
  ALL_FIELDS_FAILURE: 'ALL_FIELDS_FAILURE',
  ALL_TABLE_FIELDS_FAILURE: 'ALL_TABLE_FIELDS_FAILURE',
  ALL_FIELDS_DATA_CHANGE: 'ALL_FIELDS_DATA_CHANGE',
  ALL_TABLE_FIELDS_DATA_CHANGE: 'ALL_TABLE_FIELDS_DATA_CHANGE',
  FLOW_CLEAR: 'FLOW_CLEAR',
  DELETE_STEP_STARTED: 'DELETE_STEP_STARTED',
  DELETE_STEP_SUCCESS: 'DELETE_STEP_SUCCESS',
  DELETE_STEP_FAILURE: 'DELETE_STEP_FAILURE',
  ENABLE_EDIT_FLOW_VIEW: 'ENABLE_EDIT_FLOW_VIEW',
  EDIT_FLOW_STARTED: 'EDIT_FLOW_STARTED',
  EDIT_FLOW_STOP: 'EDIT_FLOW_STOP',
  RULE_FIELD_TYPE_CHANGE_FLOW_STARTED:
    'RULE_FIELD_TYPE_CHANGE_FLOW_STARTED',
  RULE_FIELD_TYPE_CHANGE_FLOW_STOP:
    'RULE_FIELD_TYPE_CHANGE_FLOW_STOP',
  GET_ACCOUNT_CONFIG_STARTED: 'GET_ACCOUNT_CONFIG_STARTED',
  GET_ACCOUNT_CONFIG_FAILED: 'GET_ACCOUNT_CONFIG_FAILED',
  GET_ACCOUNT_CONFIG_SUCCESS: 'GET_ACCOUNT_CONFIG_SUCCESS',
  SET_DELETE_FLOW_MODAL_VISIBILITY:
    'SET_DELETE_FLOW_MODAL_VISIBILITY',
  SET_METRICS: 'SET_METRICS',
  EDIT_INITIAL_LOADING: 'EDIT_INITIAL_LOADING',
  DEFAULT_VALUE_SAVE_RULE: 'SAVE_RULE_DEFAULT_VALUE_FLOW',
  SAVE_RULE: 'CREATE_FLOW_SAVE_RULE',
  SET_VISIBILITY_DATA: 'CREATE_FLOW_SET_VISIBILITY_FIELD_DATA',
  CLEAR_ADD_FORM_FIELDS_DROPDOWN_DATA: 'CLEAR_ADD_FORM_FIELDS_DROPDOWN_DATA',
  GET_RULE_STARTED: 'CREATE_FLOW_GET_RULE_STARTED',
  GET_RULE_STOPPED: 'CREATE_FLOW_GET_RULE_STOPPED',
};

export const CHAT = {
  ROOM_ID: 'ROOM_ID',
  SOCKET_MESSAGES: 'SOCKET_MESSAGES',
  TYPING_LIST: 'TYPING_LIST',
  EMPTY: 'EMPTY',
  ADD_NEW_USER_METADATA: 'ADD_NEW_USER_METADATA',
  UPDATE_ALL_USERS_METADATA: 'UPDATE_ALL_USERS_METADATA',
};

export const CHAT_SCREEN = {
  GLOBAL_NOTICATION_COUNT_SUCCESS: 'GLOBAL_NOTICATION_COUNT_SUCCESS',
  GLOBAL_NOTICATION_COUNT_FAILURE: 'GLOBAL_NOTICATION_COUNT_FAILURE',
  GET_THREADS_BY_USER_SUCCESS: 'GET_THREADS_BY_USER_SUCESS',
  GET_THREADS_BY_USER_FAILURE: 'GET_THREADS_BY_USER_FAILURE',
  GET_THREADS_BY_USER_EMPTY: 'GET_THREADS_BY_USER_EMPTY',
  UPDATE_CHAT_THREADS: 'UPDATE_CHAT_THREADS',
  UPDATE_SELECTED_CHAT_THREADS: 'UPDATE_SELECTED_CHAT_THREADS',
  UPDATE_SEARCH_LIST: 'UPDATE_SEARCH_LIST',
  CLEAR_SEARCH_LIST: 'CLEAR_SEARCH_LIST',
  UPDATE_SEARCH_VALUE: 'UPDATE_SEARCH_VALUE',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
};

export const API_STATUS = {
  STARTED: 'STARTED',
  STOP: 'STOP',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  CANCEL: 'CANCEL',
  SEARCH_FAILURE: 'SEARCH_FAILURE',
  LANDING_STARTED: 'LANDING_STARTED',
  LANDING_SUCCESS: 'LANDING_SUCCESS',
  LANDING_FAILURE: 'LANDING_FAILURE',
};

const STRINGS = {
  ALL_USERS: 'ALL_USERS',
  USER: 'USER',
  CHAT: 'CHAT',
  CHAT_SCREEN: 'CHAT_SCREEN',
  TEAM: 'TEAM',
  DATA_CHANGE: 'DATA_CHANGE',
  UPDATE_STATE: 'UPDATE_STATE',
  COMMON_HEADER_CHANGE: 'COMMON_HEADER_CHANGE',
  PD_TAB_INDEX: 'PD_TAB_INDEX',
  PD_VIEW_INDEX: 'PD_VIEW_INDEX',
  SET_STATE: 'SET_STATE',
  POST_CANCEL: 'POST_CANCEL',
  CLEAR: 'CLEAR',
  RELOAD: 'RELOAD',
  SEARCH_STARTED: 'SEARCH_STARTED',
  TASK_LIST: 'TASK_LIST',
  USAGE_SUMMARY_STARTED: 'USAGE_SUMMARY_STARTED',
  USERS_SUMMARY_STARTED: 'USERS_SUMMARY_STARTED',
  TASK_RESULT: 'TASK_RESULT',
  TASK_LOAD_MORE: 'TASK_LIST_LOAD_MORE',
  SEARCH_LIST_LOAD_MORE: 'TASK_SEARCH_LOAD_MORE',
  TASK_COUNT: 'TASK_COUNT',
  REQUIRED_TASK_ACTION: 'REQUIRED_TASK_ACTION',
  FLOW_LIST: 'FLOW_LIST',
  STARTED_FLOW_LIST: 'STARTED_FLOW_LIST',
  USER_PREFERENCE: 'USER_PREFERENCE',
  LANGUAGE_LOOK_UP: 'LANGUAGE_LOOK_UP',
  TIME_ZONE_LOOK_UP: 'TIME_ZONE_LOOK_UP',
  LOCALE_LOOK_UP: 'LOCALE_LOOK_UP',
  DEFAULT_VALUE_RULE: 'DEFAULT_VALUE_RULE',
  EXTERNAL_FIELD_VALUES: 'EXTERNAL_FIELD_VALUES',
  VISIBILITY_EXTERNAL_FIELD_VALUES: 'VISIBILITY_EXTERNAL_FIELDS',
  TABLE_VALIDATION_FIELD_VALUES: 'TABLE_VALIDATION_FIELD_VALUES',
  DATALIST_FIELDS: 'DATALIST_FIELDS',
  DATALIST_FIELD_VALUES: 'DATALIST_FIELD_VALUES',
  VISIBILITY_OPERATORS: 'VISIBILITY_OPERATORS',
  VISIBILITY_EXTERNAL_FIELD_REDUCER: 'VISIBILITY_EXTERNAL_FIELD_REDUCER',
  UPDATE_FIELD: 'UPDATE_FIELD',
  UPDATE_ACTION: 'UPDATE_ACTION',
  SELECTED_USER: 'SELECTED_USER',
  GET_INDUSTRY_LIST_INFINITE_SCROLL_STARTED:
    'GET_INDUSTRY_LIST_INFINITE_SCROLL_STARTED',
  UPDATE_MEMBER_SEARCH_VALUE: 'UPDATE_MEMBER_SEARCH_VALUE',
  ERROR_LIST: 'ERROR_LIST',
  EDIT_CLEAR: 'EDIT_CLEAR',
  DETAILS_BY_ID: 'DETAILS_BY_ID',
  SET_IMAGE: 'SET_IMAGE',
  SET_IS_ENABLE_BUTTON: 'SET_IS_ENABLE_BUTTON',
  COMPARE_OBJECTS_TO_ENABLE_BUTTON: 'COMPARE_OBJECTS_TO_ENABLE_BUTTON',
  UPDATE_TEAM_DATA_SUCCESS: 'UPDATE_TEAM_DATA_SUCCESS',
  UPLOAD_SIGNED_URL_SUCCESS: 'UPLOAD_SIGNED_URL_SUCCESS',
  LANGAUGE_AND_CALENDAR_ADMIN: 'LANGAUGE_AND_CALENDAR_ADMIN',
  HOLIDAY_DETAILS: 'HOLIDAY_DETAILS',
  HOLIDAY_LIST: 'HOLIDAY_LIST',
  UPDATE: 'UPDATE',
  ACCOUNT_CONFIGURATION_ADMIN: 'ACCOUNT_CONFIGURATION_ADMIN',
  AUTH_ACCOUNT_CONFIGURATION_ADMIN: 'AUTH_ACCOUNT_CONFIGURATION_ADMIN',
  USER_MANAGEMENT_ADMIN: 'USER_MANAGEMENT_ADMIN',
  ADMIN_SETTINGS: 'ADMIN_SETTINGS',
  ADD_MEMBER: 'ADD_MEMBER',
  ADD_ROLE: 'ADD_ROLE',
  ADD_BUSINESS_UNIT: 'ADD_BUSINESS_UNIT',
  TASK_CONTENT: 'TASK_CONTENT',
  TASK_ASSIGNEES_COMPLETED: 'TASK_ASSIGNEES_COMPLETED',
  TASK_ASSIGNEES_RESPONSE: 'TASK_ASSIGNEES_RESPONSE',
  TASK_METADATA: 'TASK_METADATA',
  USER_SETTINGS: 'USER_SETTINGS',
  FILE_UPLOAD_PROGRESS_CHANGE: 'FILE_UPLOAD_PROGRESS_CHANGE',
  ACCOUNT_SETTINGS: 'ACCOUNT_SETTINGS',
  COVER_CONTENT_SETTINGS: 'COVER_CONTENT_SETTINGS',
  TASK_ACTION_HISTORY: 'TASK_ACTION_HISTORY',
  LAYOUT: 'LAYOUT',
  EXTERNAL_SIGNIN: 'EXTERNAL_SIGNIN',
  LAYOUT_WITH_SIDEBAR: 'LAYOUT_WITH_SIDEBAR',
  REFRESH_API_CALL_STARTED: 'REFRESH_API_STARTED',
  RULE_FIELD_TYPE_CHANGE_TASK_STARTED: 'RULE_FIELD_TYPE_CHANGE_TASK_STARTED',
  RULE_FIELD_TYPE_CHANGE_TASK_SUCCESS: 'RULE_FIELD_TYPE_CHANGE_TASK_SUCCESS',
  RULE_FIELD_TYPE_CHANGE_TASK_FAILED: 'RULE_FIELD_TYPE_CHANGE_TASK_FAILED',
  GET_ALL_FIELDS_STARTED: 'GET_ALL_FIELDS_STARTED',
  GET_ALL_FIELDS_SUCCESS: 'GET_ALL_FIELDS_SUCCESS',
  GET_ALL_FIELDS_FAILED: 'GET_ALL_FIELDS_FAILED',
  REFRESH_API_CALL_COMPLETED: 'REFRESH_API_COMPLETED',
  USER_SEARCH: 'USER_SEARCH',
  REFRESH_TASK_LIST_FROM_INITIATE_FLOW_STARTED:
    'REFRESH_TASK_LIST_FROM_INITIATE_FLOW_STARTED',
  REFRESH_TASK_LIST_FROM_INITIATE_FLOW_SUCCESS:
    'REFRESH_TASK_LIST_FROM_INITIATE_FLOW_SUCCESS',
  FLOATING_ACTION_MENU_START_SECTION: 'FLOATING_ACTION_MENU_START_SECTION',
  HIDE_TASK_LIST_STARTED: 'HIDE_TASK_LIST_STARTED',
  HIDE_TASK_LIST_COMPLETED: 'HIDE_TASK_LIST_COMPLETED',
  INITIATE_FLOW: 'INITIATE_FLOW',
  SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
  SET_FLOW_NAME: 'SET_FLOW_NAME',
  SET_FLOW_SHORT_CODE: 'SET_FLOW_SHORT_CODE',
  SET_FLOW_DESCRIPTION: 'SET_FLOW_DESCRIPTION',
  SET_FLOW_COLOR: 'SET_FLOW_COLOR',
  SET_FLOW_OWNERS: 'SET_FLOW_OWNERS',
  SET_FLOW_ADMINS: 'SET_FLOW_ADMINS',
  CAN_REASSIGN: 'CAN_REASSIGN',
  SET_FLOW_DOCUMENT_DETAILS: 'SET_FLOW_DOCUMENT_DETAILS',
  SET_FILTER: 'SET_FILTER',
  SET_FILTER_FIELD_PARAM: 'SET_FILTER_FIELD_PARAM',
  SET_CHART: 'SET_CHART',
  CLEAR_CHART: 'CLEAR_CHART',
  SET_SEARCH: 'SET_SEARCH',
  CLEAR_SEARCH: 'CLEAR_SEARCH',
  SET_SAVED_SEARCH: 'SET_SAVED_SEARCH',
  CLEAR_SAVED_SEARCH: 'CLEAR_SAVED_SEARCH',
  SET_INSTANCE: 'SET_INSTANCE',
  SET_INSTANCE_DATA_STARTED: 'SET_INSTANCE_DATA_STARTED',
  SET_INSTANCE_DATA: 'SET_INSTANCE_DATA',
  FLOW_DASHBOARD: 'FLOW_DASHBOARD',
  ACCESS_BY_UUID_SUCCESS: 'ACCESS_BY_UUID_SUCCESS',
  INSTANCES_BY_UUID_SUCCESS: 'INSTANCES_BY_UUID_SUCCESS',
  INSTANCE_PAGINATION_DATA: 'INSTANCE_PAGINATION_DATA',
  SAVED_SEARCH: 'SAVED_SEARCH',
  SAVED_SEARCH_STARTED: 'SAVED_SEARCH_STARTED',
  SAVED_SEARCH_STOP: 'SAVED_SEARCH_STOP',
  SET_SORT: 'SET_SORT',
  SET_TAB_INDEX: 'SET_TAB_INDEX',
  CLEAR_REPORTING_MANAGER: 'CLEAR_REPORTING_MANAGER',
  TASK_RESPONSE_SUMMARY: 'TASK_RESPONSE_SUMMARY',
  TASK_FORM_DETAILS: 'TASK_FORM_DETAILS',
  INSTANCE_STARTED: 'INSTANCE_STARTED',
  INSTANCE_DETAILS_STARTED: 'INSTANCE_DETAILS_STARTED',
  INSTANCE_SUMMARY_STARTED: 'INSTANCE_SUMMARY_STARTED',
  INSTANCE_SUMMARY_FAILURE: 'INSTANCE_SUMMARY_FAILURE',
  DASHBOARD_FILTER_STARTED: 'DASHBOARD_FILTER_STARTED',
  INSTANCE_BODY_DATA_STARTED: 'INSTANCE_BODY_DATA_STARTED',
  INSTANCE_CLEAR: 'INSTANCE_CLEAR',
  STATE_CHANGE: 'STATE_CHANGE',
  INSTANCE_DETAILS: 'INSTANCE_DETAILS',
  INSTANCE_SUMMARY: 'INSTANCE_SUMMARY',
  INSTANCE_SUMMARY_CLEAR: 'INSTANCE_SUMMARY_CLEAR',
  FIELD_SUGGESTION: 'FIELD_SUGGESTION',
  FIELD_VISIBILITY: 'FIELD_VISIBILITY',
  METRIC_DISPLAY_DIMENSION: 'METRIC_DISPLAY_DIMENSION',
  FIELD_AUTO_COMPLETE_STARTED: 'FIELD_AUTO_COMPLETE_STARTED',
  FIELD_AUTO_COMPLETE_SUCCESS: 'FIELD_AUTO_COMPLETE_SUCCESS',
  FIELD_AUTO_COMPLETE_FAILED: 'FIELD_AUTO_COMPLETE_FAILED',
  CATEGORY_LIST: 'CATEGORY_LIST',
  ADD_CATEGORY_TEXT: 'ADD_CATEGORY_TEXT',
  PAGE_CHANGE: 'PAGE_CHANGE',
  PAGE_LOAD: 'PAGE_LOAD',
  ROW_COUNT_CHANGE: 'ROW_COUNT_CHANGE',
  NAVBAR: 'NAVBAR_STRING',
  SEARCH_RESULTS: 'SEARCH_RESULTS',
  DATALIST_LIST: 'DATALIST_LIST',
  TASK_SEARCH_START: 'TASK_SEARCH_START',
  FLOW_SEARCH_START: 'FLOW_SEARCH_START',
  DATALIST_SEARCH_START: 'DATALIST_SEARCH_START',
  TASK_SEARCH_FAIL: 'TASK_SEARCH_FAIL',
  FLOW_SEARCH_FAIL: 'FLOW_SEARCH_FAIL',
  DATALIST_SEARCH_FAIL: 'DATALIST_SEARCH_FAIL',
  SEARCH_FAILURE: 'SEARCH_FAILURE',
  ACCOUNT_SIGNUP_MODULE: 'ACCOUNT_SIGNUP_MODULE',
  ACCOUNT_STARTED: 'ACCOUNT_STARTED',
  ACCOUNT_SUCCESS: 'ACCOUNT_SUCCESS',
  ACCOUNT_FAILURE: 'ACCOUNT_FAILURE',
  ACCOUNT_SET_CHANGE: 'ACCOUNT_SET_CHANGE',
  LOADING_STATUS: 'LOADING_STATUS',
  UPDATE_INVOICE_DATA: ' UPDATE_INVOICE_DATA',
  BILLING_MODULE_PAGE_CHANGE: 'BILLING_MODULE_PAGE_CHANGE',
  GET_ALL_INVOICE_STARTED: 'GET_ALL_INVOICE_STARTED',
  GET_ALL_SUBS_SUCCESS: 'GET_ALL_SUBS_SUCCESS',
  SAVE_PAYMENT_SETSTATE: 'SAVE_PAYMENT_SETSTATE',
  CHANGE_PAY_SCREEN: 'CHANGE_PAY_SCREEN',
  SET_PAYMENT_METHOD_STATE_CHANGE: 'SET_PAYMENT_METHOD_STATE_CHANGE',
  SELECTED_USER_DATA: 'SELECTED_USER_DATA',
  ADD_MEMBER_DATA: 'ADD_MEMBER_DATA',
  BILLING_MODULE: 'BILLING_MODULE',
  CHANGE_EDIT: 'CHANGE_EDIT',
  PAYMENT_DATA_STARTED: 'PAYMENT_DATA_STARTED',
  PAYMENT_DATA_SUCCESS: 'PAYMENT_DATA_SUCCESS',
  PAYMENT_DATA_FAILURE: 'PAYMENT_DATA_FAILURE',
  UPDATED_PAYMENT_DATA_FAILURE: 'UPDATED_PAYMENT_DATA_FAILURE',
  UPDATED_PAYMENT_DATA_SUCCESS: 'UPDATED_PAYMENT_DATA_SUCCESS',
  CUSTOMIZED_PAYMENT_DATA: 'CUSTOMIZED_PAYMENT_DATA',
  CUSTOMIZED_PAYMENT_PROFILE_DATA: 'CUSTOMIZED_PAYMENT_PROFILE_DATA',
  SUBSCRIPTION_DATA_SUCESS: ' SUBSCRIPTION_DATA_SUCESS',
  SUBSCRIPTION_DATA_FAILER: ' SUBSCRIPTION_DATA_FAILER',
  MEMBER_SEARCH_VALUE: 'MEMBER_SEARCH_VALUE',
  CLEAR_SET_PAYPROFILE: 'CLEAR_SET_PAYPROFILE',
  USAGE_DASHBOARD: 'USAGE_DASHBOARD',
  FLOW_LIST_STARTED: 'FLOW_LIST_STARTED',
  TASK_FLOW_LIST_STARTED: 'TASK_FLOW_LIST_STARTED',
  USER_TASK_LIST_STARTED: 'USER_TASK_LIST_STARTED',
  FLOW_LIST_SUCCESS: 'FLOW_LIST_SUCCESS',
  TASK_FLOW_LIST_SUCCESS: 'TASK_FLOW_LIST_SUCCESS',
  USER_TASK_LIST_SUCCESS: 'USER_TASK_LIST_SUCCESS',
  USAGE_SUMMARY_SUCCESS: 'USAGE_SUMMARY_SUCCESS',
  USERS_SUMMARY_SUCCESS: 'USERS_SUMMARY_SUCCESS',
  FLOW_LIST_FAILURE: 'FLOW_LIST_FAILURE',
  TASK_FLOW_LIST_FAILURE: 'TASK_FLOW_LIST_FAILURE',
  USER_TASK_LIST_FAILURE: 'USER_TASK_LIST_FAILURE',
  USAGE_SUMMARY_FAILURE: 'USAGE_SUMMARY_FAILURE',
  USERS_SUMMARY_FAILURE: 'USERS_SUMMARY_FAILURE',
  ADMIN_ACCOUNT_LIST: 'ADMIN_ACCOUNT_LIST',
  ADD_ADMIN_ACCOUNT_TEXT: 'ADD_ADMIN_ACCOUNT_TEXT',
  ADMIN_ACCOUNT_DETAILS: 'ADMIN_ACCOUNT_DETAILS',
  ADMIN_ACCOUNT_SUMMARY: 'ADMIN_ACCOUNT_SUMMARY',
  ADMIN_ACCOUNT_SUMMARY_ACTION_PER_SESSION:
    'ADMIN_ACCOUNT_SUMMARY_ACTION_PER_SESSION',
  ADMIN_ACCOUNT_SUMMARY_SESSION_COUNT: 'ADMIN_ACCOUNT_SUMMARY_SESSION_COUNT',
  ADMIN_ACCOUNT_SUMMARY_ACTIVE_USER_COUNT:
    'ADMIN_ACCOUNT_SUMMARY_ACTIVE_USER_COUNT',
  ADMIN_ACCOUNT_SUMMARY_RETENTION_RATE: 'ADMIN_ACCOUNT_SUMMARY_RETENTION_RATE',
  ACCOUNT_CUSTOMISED_DATA: 'ACCOUNT_CUSTOMISED_DATA',
  ADMIN_ACCOUNT_USAGE_SUMMARY: 'ADMIN_ACCOUNT_USAGE_SUMMARY',
  ACCOUNT_SEARCH_VALUE_CHANGE: 'ACCOUNT_SEARCH_VALUE_CHANGE',
  CREATE_TEAM_CLEAR: 'CREATE_TEAM_CLEAR',
  TEAM_LIST_CLEAR: 'TEAM_LIST_CLEAR',
  BILLING_REDIRECT: 'BILLING_REDIRECT',
  TEAM_DETAILS_CLEAR: 'TEAM_DETAILS_CLEAR',
  TEAM_MEMBERS_CLEAR: 'TEAM_MEMBERS_CLEAR',
  FORMULA_BUILDER: 'FORMULA_BUILDER',
  DOWNLOAD_WINDOW: 'DOWNLOAD_WINDOW',
  WELCOME_INSIGHTS: 'WELCOME_INSIGHTS',
  TABLE_COLUMN_VISIBILITY: 'TABLE_COLUMN_VISIBILITY',
  WEBPAGE_EMBED_WHITELIST: 'WEBPAGE_EMBED_WHITELIST',
  MFA: 'MFA',
  ML_MODEL: 'MLMODEL',
  ML_MODEL_FLOW_LIST: 'ML_MODEL_FLOW_LIST',
};

export const APPLICATION = {
  APPLICATION_LIST_DATA_CHANGE: 'APPLICATION_LIST_DATA_CHANGE',
  APPLICATION_DATA_CHANGE: 'APPLICATION_DATA_CHANGE',
  APPLICATION_DATA_CLEAR: 'APPLICATION_DATA_CLEAR',
  APPLICATION_STATE_CHANGE: 'APPLICATION_STATE_CHANGE',
  PAGE_STATE_CHANGE: 'PAGE_STATE_CHANGE',
  CLEAR_APPLICATION_STATE: 'CLEAR_APPLICATION_STATE',
  COMPONENT_DATA_CHANGE: 'COMPONENT_DATA_CHANGE',
  CONFIG_DATA_CHANGE: 'CONFIG_DATA_CHANGE',
  CLEAR_STATE: 'CLEAR_STATE',
  SYSTEM_DIRECTORY_STATE_CHANGE: 'SYSTEM_DIRECTORY_STATE_CHANGE',
  RESET_APP_LISTING: 'RESET_APP_LISTING',
  APP_ACTIVE_COMPONENT_DATA_CHANGE: 'APP_ACTIVE_COMPONENT_DATA_CHANGE',
  APPLICATION_CLEAR: 'APPLICATION_CLEAR',
  APPLICATION_DELETE_ANYWAY_RESET: 'APPLICATION_DELETE_ANYWAY_RESET',
  APPLICATION_PAGE_SETTING_CLEAR: 'APPLICATION_PAGE_SETTING_CLEAR',
};
export const LAYOUT = {
  STARTED: STRINGS.LAYOUT.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.LAYOUT.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.LAYOUT.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.LAYOUT.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.LAYOUT.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.LAYOUT.concat(STRINGS.CLEAR),
};

export const EXTERNAL_SIGNIN = {
  STARTED: STRINGS.EXTERNAL_SIGNIN.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.EXTERNAL_SIGNIN.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.EXTERNAL_SIGNIN.concat(API_STATUS.FAILURE),
};

export const LAYOUT_WITH_SIDEBAR = {
  // STARTED: STRINGS.LAYOUT_WITH_SIDEBAR.concat(API_STATUS.STARTED),
  // SUCCESS: STRINGS.LAYOUT_WITH_SIDEBAR.concat(API_STATUS.SUCCESS),
  // FAILURE: STRINGS.LAYOUT_WITH_SIDEBAR.concat(API_STATUS.FAILURE),
  // CANCEL: STRINGS.LAYOUT_WITH_SIDEBAR.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.LAYOUT_WITH_SIDEBAR.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.LAYOUT_WITH_SIDEBAR.concat(STRINGS.CLEAR),
};

export const CHAT_ACTIONS = {
  STARTED: STRINGS.CHAT.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.CHAT.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.CHAT.concat(API_STATUS.FAILURE),
  EMPTY: STRINGS.CHAT.concat(CHAT.EMPTY),
  CANCEL: STRINGS.CHAT.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.CHAT.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.CHAT.concat(STRINGS.CLEAR),
  ROOM_ID: STRINGS.CHAT.concat(CHAT.ROOM_ID),
  SOCKET_MESSAGES: STRINGS.CHAT.concat(CHAT.SOCKET_MESSAGES),
  TYPING_LIST: STRINGS.CHAT.concat(CHAT.TYPING_LIST),
  ADD_NEW_USER_METADATA: STRINGS.CHAT.concat(CHAT.ADD_NEW_USER_METADATA),
  UPDATE_ALL_USERS_METADATA: STRINGS.CHAT.concat(
    CHAT.UPDATE_ALL_USERS_METADATA,
  ),
};

export const CHAT_SCREEN_ACTIONS = {
  GLOBAL_NOTICATION_COUNT_SUCCESS: STRINGS.CHAT_SCREEN.concat(
    CHAT_SCREEN.GLOBAL_NOTICATION_COUNT_SUCCESS,
  ),
  GLOBAL_NOTICATION_COUNT_FAILURE: STRINGS.CHAT_SCREEN.concat(
    CHAT_SCREEN.GLOBAL_NOTICATION_COUNT_FAILURE,
  ),
  GET_THREADS_BY_USER_SUCCESS: STRINGS.CHAT_SCREEN.concat(
    CHAT_SCREEN.GET_THREADS_BY_USER_SUCCESS,
  ),
  GET_THREADS_BY_USER_FAILURE: STRINGS.CHAT_SCREEN.concat(
    CHAT_SCREEN.GET_THREADS_BY_USER_FAILURE,
  ),
  GET_THREADS_BY_USER_EMPTY: STRINGS.CHAT_SCREEN.concat(
    CHAT_SCREEN.GET_THREADS_BY_USER_EMPTY,
  ),
  UPDATE_CHAT_THREADS: STRINGS.CHAT_SCREEN.concat(
    CHAT_SCREEN.UPDATE_CHAT_THREADS,
  ),
  UPDATE_SELECTED_CHAT_THREADS: STRINGS.CHAT_SCREEN.concat(
    CHAT_SCREEN.UPDATE_SELECTED_CHAT_THREADS,
  ),
  UPDATE_SEARCH_LIST: STRINGS.CHAT_SCREEN.concat(
    CHAT_SCREEN.UPDATE_SEARCH_LIST,
  ),
  CLEAR_SEARCH_LIST: STRINGS.CHAT_SCREEN.concat(CHAT_SCREEN.CLEAR_SEARCH_LIST),
  UPDATE_SEARCH_VALUE: STRINGS.CHAT_SCREEN.concat(
    CHAT_SCREEN.UPDATE_SEARCH_VALUE,
  ),
  CLEAR: STRINGS.CHAT_SCREEN.concat(STRINGS.CLEAR),
  STARTED: STRINGS.CHAT_SCREEN.concat(API_STATUS.STARTED),
  SEARCH_STARTED: STRINGS.CHAT_SCREEN.concat(STRINGS.SEARCH_STARTED),
  OPEN_MODAL: STRINGS.CHAT_SCREEN.concat(CHAT_SCREEN.OPEN_MODAL),
  CLOSE_MODAL: STRINGS.CHAT_SCREEN.concat(CHAT_SCREEN.CLOSE_MODAL),
  CANCEL: STRINGS.CHAT_SCREEN.concat(API_STATUS.CANCEL),
};

export const USER_SEARCH_ACTION = {
  SET_SEARCH_VALUE: STRINGS.USER_SEARCH.concat(STRINGS.DATA_CHANGE),
};

export const TASK_LIST_ACTION = {
  STARTED: STRINGS.TASK_LIST.concat(API_STATUS.STARTED),
  STARTED_NO_LOADING: STRINGS.TASK_LIST.concat(STRINGS.LOADING_STATUS),
  TASK_RESULT_STARTED: STRINGS.TASK_RESULT.concat(API_STATUS.STARTED),
  LOAD_MORE: STRINGS.TASK_LOAD_MORE.concat(API_STATUS.STARTED),
  LOAD_MORE_COMPLETED: STRINGS.TASK_LOAD_MORE.concat(API_STATUS.SUCCESS),
  SEARCH_LOAD_MORE: STRINGS.SEARCH_LIST_LOAD_MORE.concat(API_STATUS.STARTED),
  SEARCH_LOAD_MORE_COMPLETED: STRINGS.SEARCH_LIST_LOAD_MORE.concat(
    API_STATUS.SUCCESS,
  ),
  SUCCESS: STRINGS.TASK_LIST.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.TASK_LIST.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.TASK_LIST.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.TASK_LIST.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.TASK_LIST.concat(STRINGS.CLEAR),

  REFRESH_API_CALL_STARTED: STRINGS.TASK_LIST.concat(
    STRINGS.REFRESH_API_CALL_STARTED,
  ),
  RULE_FIELD_TYPE_CHANGE_TASK_STARTED: STRINGS.TASK_LIST.concat(
    STRINGS.RULE_FIELD_TYPE_CHANGE_TASK_STARTED,
  ),
  RULE_FIELD_TYPE_CHANGE_TASK_SUCCESS: STRINGS.TASK_LIST.concat(
    STRINGS.RULE_FIELD_TYPE_CHANGE_TASK_SUCCESS,
  ),
  RULE_FIELD_TYPE_CHANGE_TASK_FAILED: STRINGS.TASK_LIST.concat(
    STRINGS.RULE_FIELD_TYPE_CHANGE_TASK_FAILED,
  ),
  GET_ALL_FIELDS_STARTED: STRINGS.TASK_LIST.concat(
    STRINGS.GET_ALL_FIELDS_STARTED,
  ),
  GET_ALL_FIELDS_SUCCESS: STRINGS.TASK_LIST.concat(
    STRINGS.GET_ALL_FIELDS_SUCCESS,
  ),
  GET_ALL_FIELDS_FAILED: STRINGS.TASK_LIST.concat(
    STRINGS.GET_ALL_FIELDS_FAILED,
  ),
  REFRESH_API_CALL_COMPLETED: STRINGS.TASK_LIST.concat(
    STRINGS.REFRESH_API_CALL_COMPLETED,
  ),
  REFRESH_TASK_LIST_FROM_INITIATE_FLOW_STARTED: STRINGS.TASK_LIST.concat(
    STRINGS.REFRESH_TASK_LIST_FROM_INITIATE_FLOW_STARTED,
  ),
  REFRESH_TASK_LIST_FROM_INITIATE_FLOW_SUCCESS: STRINGS.TASK_LIST.concat(
    STRINGS.REFRESH_TASK_LIST_FROM_INITIATE_FLOW_SUCCESS,
  ),
  FIELD_AUTO_COMPLETE_STARTED: STRINGS.TASK_LIST.concat(
    STRINGS.FIELD_AUTO_COMPLETE_STARTED,
  ),
  FIELD_AUTO_COMPLETE_SUCCESS: STRINGS.TASK_LIST.concat(
    STRINGS.FIELD_AUTO_COMPLETE_SUCCESS,
  ),
  FIELD_AUTO_COMPLETE_FAILED: STRINGS.TASK_LIST.concat(
    STRINGS.FIELD_AUTO_COMPLETE_FAILED,
  ),
};

export const TASK_COUNT_ACTION = {
  STARTED: STRINGS.TASK_COUNT.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.TASK_COUNT.concat(API_STATUS.SUCCESS),
};
export const TASK_CONTENT_ACTION = {
  STARTED: STRINGS.TASK_CONTENT.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.TASK_CONTENT.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.TASK_CONTENT.concat(API_STATUS.FAILURE),
  SERVER_ERROR: STRINGS.TASK_CONTENT.concat('SERVER_ERROR'),
  CANCEL: STRINGS.TASK_CONTENT.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.TASK_CONTENT.concat(STRINGS.DATA_CHANGE),
  TASK_CONTENT_RESPONDANTS_SUMMARY_DATA_CHANGE:
    'TASK_CONTENT_RESPONDANTS_SUMMARY_DATA_CHANGE',
  FILE_UPLOAD_PROGRESS_CHANGE: STRINGS.TASK_CONTENT.concat(
    STRINGS.FILE_UPLOAD_PROGRESS_CHANGE,
  ),
  FORM_UPLOAD_FIELD_CHANGE: STRINGS.TASK_CONTENT.concat(
    'FORM_UPLOAD_FIELD_CHANGE',
  ),
  FORM_TABLE_UPLOAD_FIELD_CHANGE: STRINGS.TASK_CONTENT.concat(
    'FORM_TABLE_UPLOAD_FIELD_CHANGE',
  ),
  UPDATE_ACTIONS: STRINGS.TASK_CONTENT.concat(STRINGS.UPDATE_ACTION),
  UPDATE_FIELD: STRINGS.TASK_CONTENT.concat(STRINGS.UPDATE_FIELD),
  CLEAR: STRINGS.TASK_CONTENT.concat(STRINGS.CLEAR),
  REQUIRED_TASK_ACTION: STRINGS.TASK_CONTENT.concat(
    STRINGS.REQUIRED_TASK_ACTION,
  ),
  SET_TAB_INDEX: STRINGS.TASK_CONTENT.concat(STRINGS.SET_TAB_INDEX),
  HIDE_TASK_LIST_STARTED: STRINGS.TASK_CONTENT.concat(
    STRINGS.HIDE_TASK_LIST_STARTED,
  ),
  HIDE_TASK_LIST_COMPLETED: STRINGS.TASK_CONTENT.concat(
    STRINGS.HIDE_TASK_LIST_COMPLETED,
  ),
  SET_CANCEL_TASK_MODAL_VISIBILITY: STRINGS.TASK_CONTENT.concat(
    'SET_CANCEL_TASK_MODAL_VISIBILITY',
  ),
  SET_CANCEL_TASK_DIALOG_VISIBILITY: STRINGS.TASK_CONTENT.concat(
    'SET_CANCEL_TASK_DIALOG_VISIBILITY',
  ),
  SET_CANCEL_TASK_MESSAGE: STRINGS.TASK_CONTENT.concat(
    'SET_CANCEL_TASK_MESSAGE',
  ),
  SET_DATA_CANCEL_FORM: STRINGS.TASK_CONTENT.concat('SET_DATA_CANCEL_FORM'),
  CLEAR_TASK_CANCEL_DATA: STRINGS.TASK_CONTENT.concat('CLEAR_TASK_CANCEL_DATA'),
  TASK_CONTENT_ADD_OR_REMOVE_ASSIGNEE_SET_DATA:
    'TASK_CONTENT_ADD_OR_REMOVE_ASSIGNEE_SET_DATA',
  TASK_CONTENT_ADD_OR_REMOVE_ASSIGNEE_CLEAR_DATA:
    'TASK_CONTENT_ADD_OR_REMOVE_ASSIGNEE_CLEAR_DATA',
  MEMBER_TEAM_SEARCH_VALUE: STRINGS.TASK_CONTENT.concat(
    'MEMBER_TEAM_SEARCH_VALUE',
  ),
  SELECTED_ASSIGNEE_DATA: STRINGS.TASK_CONTENT.concat('SELECTED_ASSIGNEE_DATA'),
  UPDATE_ACTIVE_TASK: 'UPDATE_ACTIVE_TASK',
};
export const TASK_RESPONSE_SUMMARY_ACTION = {
  STARTED: STRINGS.TASK_RESPONSE_SUMMARY.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.TASK_RESPONSE_SUMMARY.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.TASK_RESPONSE_SUMMARY.concat(API_STATUS.FAILURE),
  CLEAR: STRINGS.TASK_RESPONSE_SUMMARY.concat(STRINGS.CLEAR),
};

export const TASK_FORM_DETAILS_ACTION = {
  STARTED: STRINGS.TASK_FORM_DETAILS.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.TASK_FORM_DETAILS.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.TASK_FORM_DETAILS.concat(API_STATUS.FAILURE),
  CLEAR: STRINGS.TASK_FORM_DETAILS.concat(STRINGS.CLEAR),
};

export const TASK_ASSIGNEES_COMPLETED = {
  STARTED: STRINGS.TASK_ASSIGNEES_COMPLETED.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.TASK_ASSIGNEES_COMPLETED.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.TASK_ASSIGNEES_COMPLETED.concat(API_STATUS.FAILURE),
};

export const TASK_METADATA = {
  STARTED: STRINGS.TASK_METADATA.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.TASK_METADATA.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.TASK_METADATA.concat(API_STATUS.FAILURE),
};

export const TASK_ASSIGNEES_RESPONSE = {
  STARTED: STRINGS.TASK_ASSIGNEES_RESPONSE.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.TASK_ASSIGNEES_RESPONSE.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.TASK_ASSIGNEES_RESPONSE.concat(API_STATUS.FAILURE),
};

export const FLOW_LIST_ACTION = {
  STARTED: STRINGS.FLOW_LIST.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.FLOW_LIST.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.FLOW_LIST.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.FLOW_LIST.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.FLOW_LIST.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.FLOW_LIST.concat(STRINGS.CLEAR),
  SEARCH_FAILURE: STRINGS.FLOW_LIST.concat(API_STATUS.SEARCH_FAILURE),
  REFRESH_FLOW_STARTED: STRINGS.FLOW_LIST.concat(
    STRINGS.REFRESH_API_CALL_STARTED,
  ),
  REFRESH_FLOW_COMPLETED: STRINGS.FLOW_LIST.concat(
    STRINGS.REFRESH_API_CALL_COMPLETED,
  ),
  LANDING_STARTED: STRINGS.FLOW_LIST.concat(API_STATUS.LANDING_STARTED),
  LANDING_SUCCESS: STRINGS.FLOW_LIST.concat(API_STATUS.LANDING_SUCCESS),
  LANDING_FAILURE: STRINGS.FLOW_LIST.concat(API_STATUS.LANDING_FAILURE),
};

export const STARTED_FLOW_LIST_ACTION = {
  STARTED: STRINGS.STARTED_FLOW_LIST.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.STARTED_FLOW_LIST.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.STARTED_FLOW_LIST.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.STARTED_FLOW_LIST.concat(API_STATUS.CANCEL),
  // DATA_CHANGE: STRINGS.STARTED_FLOW_LIST.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.STARTED_FLOW_LIST.concat(STRINGS.CLEAR),
  // REFRESH_FLOW_STARTED: STRINGS.STARTED_FLOW_LIST.concat(STRINGS.REFRESH_API_CALL_STARTED),
  // REFRESH_FLOW_COMPLETED: STRINGS.STARTED_FLOW_LIST.concat(STRINGS.REFRESH_API_CALL_COMPLETED),
};

export const TEAM = {
  STARTED: STRINGS.TEAM.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.TEAM.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.TEAM.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.TEAM.concat(API_STATUS.CANCEL),
  CLEAR: STRINGS.TEAM.concat(STRINGS.CLEAR),
  EDIT_CLEAR: STRINGS.TEAM.concat(STRINGS.EDIT_CLEAR),
  UPDATE_FIELD: STRINGS.TEAM.concat(STRINGS.UPDATE_FIELD),
  SELECTED_USER: STRINGS.TEAM.concat(STRINGS.SELECTED_USER),
  UPDATE_MEMBER_SEARCH_VALUE: STRINGS.TEAM.concat(
    STRINGS.UPDATE_MEMBER_SEARCH_VALUE,
  ),
  ERROR_LIST: STRINGS.TEAM.concat(STRINGS.ERROR_LIST),
  DETAILS_BY_ID_SUCCESS: STRINGS.TEAM.concat(STRINGS.DETAILS_BY_ID),
  SET_IMAGE: STRINGS.TEAM.concat(STRINGS.SET_IMAGE),
  SET_IS_ENABLE_BUTTON: STRINGS.TEAM.concat(STRINGS.SET_IS_ENABLE_BUTTON),
  COMPARE_OBJECTS_TO_ENABLE_BUTTON: STRINGS.TEAM.concat(
    STRINGS.COMPARE_OBJECTS_TO_ENABLE_BUTTON,
  ),
  UPDATE_TEAM_DATA_SUCCESS: STRINGS.TEAM.concat(
    STRINGS.UPDATE_TEAM_DATA_SUCCESS,
  ),
  UPLOAD_SIGNED_URL_SUCCESS: STRINGS.TEAM.concat(
    STRINGS.UPLOAD_SIGNED_URL_SUCCESS,
  ),
  DATA_CHANGE: STRINGS.TEAM.concat(STRINGS.DATA_CHANGE),
  CREATE_TEAM_CLEAR: STRINGS.TEAM.concat(STRINGS.CREATE_TEAM_CLEAR),
  TEAM_LIST_CLEAR: STRINGS.TEAM.concat(STRINGS.TEAM_LIST_CLEAR),
  TEAM_DETAILS_CLEAR: STRINGS.TEAM.concat(STRINGS.TEAM_DETAILS_CLEAR),
  TEAM_MEMBERS_CLEAR: STRINGS.TEAM.concat(STRINGS.TEAM_MEMBERS_CLEAR),
};

export const USER_PREFERENCE = {
  STARTED: STRINGS.USER_PREFERENCE.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.USER_PREFERENCE.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.USER_PREFERENCE.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.USER_PREFERENCE.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.USER_PREFERENCE.concat(STRINGS.DATA_CHANGE),
  POST_CANCEL: STRINGS.USER_PREFERENCE.concat(STRINGS.POST_CANCEL),
  CLEAR: STRINGS.USER_PREFERENCE.concat(STRINGS.CLEAR),
};

export const LANGUAGE_LOOK_UP = {
  STARTED: STRINGS.LANGUAGE_LOOK_UP.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.LANGUAGE_LOOK_UP.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.LANGUAGE_LOOK_UP.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.LANGUAGE_LOOK_UP.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.LANGUAGE_LOOK_UP.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.LANGUAGE_LOOK_UP.concat(STRINGS.CLEAR),
};

export const TIME_ZONE_LOOK_UP = {
  STARTED: STRINGS.TIME_ZONE_LOOK_UP.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.TIME_ZONE_LOOK_UP.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.TIME_ZONE_LOOK_UP.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.TIME_ZONE_LOOK_UP.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.TIME_ZONE_LOOK_UP.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.TIME_ZONE_LOOK_UP.concat(STRINGS.CLEAR),
};

export const DATA_ENCRYTION_REDUCER_CONSTANTS = {
  DATA_SUCCESS: 'set_request_data',
  PARAMS_SUCCESS: 'set_params_data',
  CLEAR: 'clear_request_data',
};

export const DEFAULT_VALUE_RULE_CONSTANTS = {
  STARTED: STRINGS.DEFAULT_VALUE_RULE.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.DEFAULT_VALUE_RULE.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.DEFAULT_VALUE_RULE.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.DEFAULT_VALUE_RULE.concat(API_STATUS.CANCEL),
  CLEAR: STRINGS.DEFAULT_VALUE_RULE.concat(STRINGS.CLEAR),
};

export const EXTERNAL_FIELD_VALUES_CONSTANTS = {
  STARTED: STRINGS.EXTERNAL_FIELD_VALUES.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.EXTERNAL_FIELD_VALUES.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.EXTERNAL_FIELD_VALUES.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.EXTERNAL_FIELD_VALUES.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.EXTERNAL_FIELD_VALUES.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.EXTERNAL_FIELD_VALUES.concat(STRINGS.CLEAR),
};

export const VISIBILITY_CONSTANTS = {
  TABLE_VALIDATION_FIELDS_STARTED: generateActionName(
    STRINGS.TABLE_VALIDATION_FIELD_VALUES,
    API_STATUS.STARTED,
  ),
  TABLE_VALIDATION_FIELDS_SUCCESS: generateActionName(
    STRINGS.TABLE_VALIDATION_FIELD_VALUES,
    API_STATUS.SUCCESS,
  ),
  TABLE_VALIDATION_FIELDS_FAILURE: generateActionName(
    STRINGS.TABLE_VALIDATION_FIELD_VALUES,
    API_STATUS.FAILURE,
  ),
  DATALIST_FIELDS_STARTED: generateActionName(
    STRINGS.DATALIST_FIELDS,
    API_STATUS.STARTED,
  ),
  DATALIST_FIELDS_SUCCESS: generateActionName(
    STRINGS.DATALIST_FIELDS,
    API_STATUS.SUCCESS,
  ),
  DATALIST_FIELDS_FAILURE: generateActionName(
    STRINGS.DATALIST_FIELDS,
    API_STATUS.FAILURE,
  ),
  DATALIST_FIELDS_CLEAR: generateActionName(
    STRINGS.DATALIST_FIELDS,
    STRINGS.CLEAR,
  ),
  DATALIST_FIELD_VALUES_STARTED: generateActionName(
    STRINGS.DATALIST_FIELD_VALUES,
    API_STATUS.STARTED,
  ),
  DATALIST_FIELD_VALUES_SUCCESS: generateActionName(
    STRINGS.DATALIST_FIELD_VALUES,
    API_STATUS.SUCCESS,
  ),
  DATALIST_FIELD_VALUES_FAILURE: generateActionName(
    STRINGS.DATALIST_FIELD_VALUES,
    API_STATUS.FAILURE,
  ),
  DATALIST_FIELD_VALUES_CLEAR: generateActionName(
    STRINGS.DATALIST_FIELDS,
    STRINGS.CLEAR,
  ),
  EXTERNAL_FIELDS_STARTED: generateActionName(
    STRINGS.VISIBILITY_EXTERNAL_FIELD_VALUES,
    API_STATUS.STARTED,
  ),
  EXTERNAL_FIELDS_SUCCESS: generateActionName(
    STRINGS.VISIBILITY_EXTERNAL_FIELD_VALUES,
    API_STATUS.SUCCESS,
  ),
  EXTERNAL_FIELDS_FAILURE: generateActionName(
    STRINGS.VISIBILITY_EXTERNAL_FIELD_VALUES,
    API_STATUS.FAILURE,
  ),
  EXTERNAL_FIELDS_CANCEL: generateActionName(
    STRINGS.VISIBILITY_EXTERNAL_FIELD_VALUES,
    API_STATUS.CANCEL,
  ),
  EXTERNAL_FIELDS_CLEAR: generateActionName(
    STRINGS.VISIBILITY_EXTERNAL_FIELD_VALUES,
    STRINGS.CLEAR,
  ),
  VISIBILITY_OPERATORS_STARTED: generateActionName(
    STRINGS.VISIBILITY_OPERATORS,
    API_STATUS.STARTED,
  ),
  VISIBILITY_OPERATORS_SUCCESS: generateActionName(
    STRINGS.VISIBILITY_OPERATORS,
    API_STATUS.SUCCESS,
  ),
  VISIBILITY_OPERATORS_FAILURE: generateActionName(
    STRINGS.VISIBILITY_OPERATORS,
    API_STATUS.FAILURE,
  ),
  VISIBILITY_EXTERNAL_FIELD_DATA_CHANGE: generateActionName(
    STRINGS.VISIBILITY_EXTERNAL_FIELD_VALUES,
    STRINGS.DATA_CHANGE,
  ),
  CLEAR_VISIBILITY_OPERATORS: generateActionName(
    STRINGS.VISIBILITY_OPERATORS,
    STRINGS.CLEAR,
  ),
  EXTERNAL_FIELD_REDUCER_DATA_CHANGE: generateActionName(
    STRINGS.VISIBILITY_EXTERNAL_FIELD_REDUCER,
    STRINGS.DATA_CHANGE,
  ),
  TABLE_COLUMN_VISIBILITY: generateActionName(
    STRINGS.VISIBILITY_EXTERNAL_FIELD_REDUCER,
    STRINGS.TABLE_COLUMN_VISIBILITY,
  ),
};
export const LOCALE_LOOK_UP = {
  STARTED: STRINGS.LOCALE_LOOK_UP.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.LOCALE_LOOK_UP.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.LOCALE_LOOK_UP.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.LOCALE_LOOK_UP.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.LOCALE_LOOK_UP.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.LOCALE_LOOK_UP.concat(STRINGS.CLEAR),
};

export const LANGAUGE_AND_CALENDAR_ADMIN = {
  STARTED: STRINGS.LANGAUGE_AND_CALENDAR_ADMIN.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.LANGAUGE_AND_CALENDAR_ADMIN.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.LANGAUGE_AND_CALENDAR_ADMIN.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.LANGAUGE_AND_CALENDAR_ADMIN.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.LANGAUGE_AND_CALENDAR_ADMIN.concat(STRINGS.DATA_CHANGE),
  POST_CANCEL: STRINGS.LANGAUGE_AND_CALENDAR_ADMIN.concat(STRINGS.POST_CANCEL),
  CLEAR: STRINGS.LANGAUGE_AND_CALENDAR_ADMIN.concat(STRINGS.CLEAR),
};

export const HOLIDAY_DETAILS = {
  STARTED: STRINGS.HOLIDAY_DETAILS.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.HOLIDAY_DETAILS.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.HOLIDAY_DETAILS.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.HOLIDAY_DETAILS.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.HOLIDAY_DETAILS.concat(STRINGS.DATA_CHANGE),
  POST_CANCEL: STRINGS.HOLIDAY_DETAILS.concat(STRINGS.POST_CANCEL),
  CLEAR: STRINGS.HOLIDAY_DETAILS.concat(STRINGS.CLEAR),
  UPDATE: STRINGS.HOLIDAY_DETAILS.concat(STRINGS.UPDATE),
};

export const HOLIDAY_LIST = {
  DATA_CHANGE: STRINGS.HOLIDAY_LIST.concat(STRINGS.DATA_CHANGE),
};

export const ACCOUNT_CONFIGURATION_ADMIN = {
  STARTED: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(STRINGS.DATA_CHANGE),
  POST_CANCEL: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(STRINGS.POST_CANCEL),
  CLEAR: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(STRINGS.CLEAR),
  UPDATE: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(STRINGS.UPDATE),
};

export const AUTH_ACCOUNT_CONFIGURATION_ADMIN = {
  STARTED: STRINGS.AUTH_ACCOUNT_CONFIGURATION_ADMIN.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(STRINGS.DATA_CHANGE),
  POST_CANCEL: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(STRINGS.POST_CANCEL),
  CLEAR: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(STRINGS.CLEAR),
  UPDATE: STRINGS.ACCOUNT_CONFIGURATION_ADMIN.concat(STRINGS.UPDATE),
};

export const USER_MANAGEMENT_ADMIN = {
  STARTED: STRINGS.USER_MANAGEMENT_ADMIN.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.USER_MANAGEMENT_ADMIN.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.USER_MANAGEMENT_ADMIN.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.USER_MANAGEMENT_ADMIN.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.USER_MANAGEMENT_ADMIN.concat(STRINGS.DATA_CHANGE),
  POST_CANCEL: STRINGS.USER_MANAGEMENT_ADMIN.concat(STRINGS.POST_CANCEL),
  CLEAR: STRINGS.USER_MANAGEMENT_ADMIN.concat(STRINGS.CLEAR),
  UPDATE: STRINGS.USER_MANAGEMENT_ADMIN.concat(STRINGS.UPDATE),
};

export const ADMIN_SETTINGS = {
  STARTED: STRINGS.ADMIN_SETTINGS.concat(API_STATUS.STARTED),
  FAILURE: STRINGS.ADMIN_SETTINGS.concat(API_STATUS.FAILURE),
  STATE_CHANGE: STRINGS.ADMIN_SETTINGS.concat(STRINGS.STATE_CHANGE),
};

export const USER_SETTINGS = {
  DATA_CHANGE: STRINGS.USER_SETTINGS.concat(API_STATUS.STARTED),
  CLEAR: STRINGS.USER_SETTINGS.concat(STRINGS.CLEAR),
};

export const ADD_MEMBER = {
  STARTED: STRINGS.ADD_MEMBER.concat(API_STATUS.STARTED),
  ADD_ROLE_STARTED: STRINGS.ADD_ROLE.concat(API_STATUS.STARTED),
  ADD_ROLE_SUCCESS: STRINGS.ADD_ROLE.concat(API_STATUS.SUCCESS),
  ADD_ROLE_FAILURE: STRINGS.ADD_ROLE.concat(API_STATUS.FAILURE),
  ADD_BUSINESS_UNIT_STARTED: STRINGS.ADD_BUSINESS_UNIT.concat(
    API_STATUS.STARTED,
  ),
  ADD_BUSINESS_UNIT_SUCCESS: STRINGS.ADD_BUSINESS_UNIT.concat(
    API_STATUS.SUCCESS,
  ),
  ADD_BUSINESS_UNIT_FAILURE: STRINGS.ADD_BUSINESS_UNIT.concat(
    API_STATUS.FAILURE,
  ),
  SUCCESS: STRINGS.ADD_MEMBER.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.ADD_MEMBER.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.ADD_MEMBER.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.ADD_MEMBER.concat(STRINGS.DATA_CHANGE),
  POST_CANCEL: STRINGS.ADD_MEMBER.concat(STRINGS.POST_CANCEL),
  CLEAR: STRINGS.ADD_MEMBER.concat(STRINGS.CLEAR),
  UPDATE: STRINGS.ADD_MEMBER.concat(STRINGS.UPDATE),
  CLEAR_REPORTING_MANAGER: STRINGS.ADD_MEMBER.concat(
    STRINGS.CLEAR_REPORTING_MANAGER,
  ),
  DATA_VALIDATION_FAILURE: STRINGS.ADD_MEMBER.concat(
    STRINGS.DATA_VALIDATION_FAILURE,
  ),
};

export const ACCOUNT_SETTINGS = {
  STARTED: STRINGS.ACCOUNT_SETTINGS.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.ACCOUNT_SETTINGS.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.ACCOUNT_SETTINGS.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.ACCOUNT_SETTINGS.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.ACCOUNT_SETTINGS.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.ACCOUNT_SETTINGS.concat(STRINGS.CLEAR),
  GET_INDUSTRY_LIST_INFINITE_SCROLL_STARTED: STRINGS.ACCOUNT_SETTINGS.concat(
    STRINGS.GET_INDUSTRY_LIST_INFINITE_SCROLL_STARTED,
  ),
};

export const COVER_CONTENT_SETTINGS = {
  STARTED: STRINGS.COVER_CONTENT_SETTINGS.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.COVER_CONTENT_SETTINGS.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.COVER_CONTENT_SETTINGS.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.COVER_CONTENT_SETTINGS.concat(API_STATUS.CANCEL),
  SET_STATE: STRINGS.COVER_CONTENT_SETTINGS.concat(STRINGS.SET_STATE),
  CLEAR: STRINGS.COVER_CONTENT_SETTINGS.concat(STRINGS.CLEAR),
};

export const TASK_ACTION_HISTORY = {
  STARTED: STRINGS.TASK_ACTION_HISTORY.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.TASK_ACTION_HISTORY.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.TASK_ACTION_HISTORY.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.TASK_ACTION_HISTORY.concat(API_STATUS.CANCEL),
  CLEAR: STRINGS.TASK_ACTION_HISTORY.concat(STRINGS.CLEAR),
};

export const FLOATING_ACTION_MENU_START_SECTION = {
  DATA_CHANGE: STRINGS.FLOATING_ACTION_MENU_START_SECTION.concat(
    STRINGS.DATA_CHANGE,
  ),
  STARTED: STRINGS.FLOATING_ACTION_MENU_START_SECTION.concat(
    API_STATUS.STARTED,
  ),
  SUCCESS: STRINGS.FLOATING_ACTION_MENU_START_SECTION.concat(
    API_STATUS.SUCCESS,
  ),
  FAILURE: STRINGS.FLOATING_ACTION_MENU_START_SECTION.concat(
    API_STATUS.FAILURE,
  ),
  GET_FLOW_LIST_INFINITE_SCROLL_STARTED:
    STRINGS.FLOATING_ACTION_MENU_START_SECTION.concat(
      'GET_FLOW_LIST_INFINITE_SCROLL_STARTED',
    ),
  CANCEL: STRINGS.FLOATING_ACTION_MENU_START_SECTION.concat(API_STATUS.CANCEL),
  CLEAR: STRINGS.FLOATING_ACTION_MENU_START_SECTION.concat(STRINGS.CLEAR),
  SET_SEARCH_TEXT: STRINGS.FLOATING_ACTION_MENU_START_SECTION.concat(
    STRINGS.SET_SEARCH_TEXT,
  ),
};

export const INITIATE_FLOW = {
  STARTED: STRINGS.INITIATE_FLOW.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.INITIATE_FLOW.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.INITIATE_FLOW.concat(API_STATUS.FAILURE),
};

export const FLOW_DASHBOARD = {
  STARTED: STRINGS.FLOW_DASHBOARD.concat(API_STATUS.STARTED),
  ACCESS_BY_UUID_SUCCESS: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.ACCESS_BY_UUID_SUCCESS,
  ),
  INSTANCES_BY_UUID_SUCCESS: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.INSTANCES_BY_UUID_SUCCESS,
  ),
  FAILURE: STRINGS.FLOW_DASHBOARD.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.FLOW_DASHBOARD.concat(API_STATUS.CANCEL),
  RELOAD: STRINGS.FLOW_DASHBOARD.concat(STRINGS.RELOAD),
  CLEAR: STRINGS.FLOW_DASHBOARD.concat(STRINGS.CLEAR),
  METRIC_DISPLAY_DIMENSION: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.METRIC_DISPLAY_DIMENSION,
  ),
  SET_SEARCH_TEXT: STRINGS.FLOW_DASHBOARD.concat(STRINGS.SET_SEARCH_TEXT),
  SET_FLOW_NAME: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SET_FLOW_NAME,
  ),
  SET_FLOW_SHORT_CODE: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SET_FLOW_SHORT_CODE,
  ),
  SET_FLOW_DESCRIPTION: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SET_FLOW_DESCRIPTION,
  ),
  SET_FLOW_COLOR: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SET_FLOW_COLOR,
  ),
  SET_FLOW_OWNERS: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SET_FLOW_OWNERS,
  ),
  CAN_REASSIGN: STRINGS.FLOW_DASHBOARD.concat(STRINGS.CAN_REASSIGN),
  SET_FLOW_ADMINS: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SET_FLOW_ADMINS,
  ),
  SET_FLOW_DOCUMENT_DETAILS: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SET_FLOW_DOCUMENT_DETAILS,
  ),
  SET_SORT: STRINGS.FLOW_DASHBOARD.concat(STRINGS.SET_SORT),
  DATA_CHANGE: STRINGS.FLOW_DASHBOARD.concat(STRINGS.DATA_CHANGE),
  UPDATE_STATE: STRINGS.FLOW_DASHBOARD.concat(STRINGS.UPDATE_STATE),
  PD_TAB_INDEX: STRINGS.FLOW_DASHBOARD.concat(STRINGS.PD_TAB_INDEX),
  PD_VIEW_INDEX: STRINGS.FLOW_DASHBOARD.concat(STRINGS.PD_VIEW_INDEX),

  SET_FILTER: STRINGS.FLOW_DASHBOARD.concat(STRINGS.SET_FILTER),
  SET_FILTER_FIELD_PARAM: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SET_FILTER_FIELD_PARAM,
  ),
  SET_CHART: STRINGS.FLOW_DASHBOARD.concat(STRINGS.SET_CHART),
  CLEAR_CHART: STRINGS.FLOW_DASHBOARD.concat(STRINGS.CLEAR_CHART),
  SET_SEARCH: STRINGS.FLOW_DASHBOARD.concat(STRINGS.SET_SEARCH),
  CLEAR_SEARCH: STRINGS.FLOW_DASHBOARD.concat(STRINGS.CLEAR_SEARCH),
  SET_SAVED_SEARCH: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SET_SAVED_SEARCH,
  ),
  CLEAR_SAVED_SEARCH: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.CLEAR_SAVED_SEARCH,
  ),
  SET_INSTANCE: STRINGS.FLOW_DASHBOARD.concat(STRINGS.SET_INSTANCE),
  SET_INSTANCE_DATA_STARTED: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SET_INSTANCE_DATA_STARTED,
  ),
  SET_INSTANCE_DATA: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SET_INSTANCE_DATA,
  ),
  INSTANCE_DETAILS: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.INSTANCE_DETAILS,
  ),
  INSTANCE_SUMMARY: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.INSTANCE_SUMMARY,
  ),
  INSTANCE_SUMMARY_CLEAR: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.INSTANCE_SUMMARY_CLEAR,
  ),
  INSTANCE_STARTED: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.INSTANCE_STARTED,
  ),
  INSTANCE_DETAILS_STARTED: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.INSTANCE_DETAILS_STARTED,
  ),
  INSTANCE_SUMMARY_STARTED: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.INSTANCE_SUMMARY_STARTED,
  ),
  INSTANCE_SUMMARY_FAILURE: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.INSTANCE_SUMMARY_FAILURE,
  ),
  DASHBOARD_FILTER_STARTED: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.DASHBOARD_FILTER_STARTED,
  ),
  INSTANCE_BODY_DATA_STARTED: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.INSTANCE_BODY_DATA_STARTED,
  ),
  INSTANCE_CLEAR: STRINGS.FLOW_DASHBOARD.concat(STRINGS.INSTANCE_CLEAR),
  STATE_CHANGE: STRINGS.FLOW_DASHBOARD.concat(STRINGS.STATE_CHANGE),

  INSTANCE_PAGINATION_DATA: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.INSTANCE_PAGINATION_DATA,
  ),
  SAVED_SEARCH_STARTED: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SAVED_SEARCH_STARTED,
  ),
  SAVED_SEARCH_STOP: STRINGS.FLOW_DASHBOARD.concat(
    STRINGS.SAVED_SEARCH_STOP,
  ),
  IS_ADHOC_TASK_MODAL_VISIBLE: STRINGS.FLOW_DASHBOARD.concat(
    'IS_ADHOC_TASK_MODAL_VISIBLE',
  ),
  ENTRY_TABLE_POPUP_VISIBILITY: STRINGS.FLOW_DASHBOARD.concat(
    'ENTRY_TABLE_POPUP_VISIBILITY',
  ),
  SET_CUSTOM_IDENTIFIER: STRINGS.FLOW_DASHBOARD.concat(
    'SET_CUSTOM_IDENTIFIER',
  ),
  SET_REFERENCE_ID: STRINGS.FLOW_DASHBOARD.concat('SET_REFERENCE_ID'),
  CLEAR_REFERENCE_ID: STRINGS.FLOW_DASHBOARD.concat('CLEAR_REFERENCE_ID'),
  REVERT_TO_PREVIOUS_SEARCH: STRINGS.FLOW_DASHBOARD.concat(
    'REVERT_TO_PREVIOUS_SEARCH',
  ),
  SET_FLOW_ID: STRINGS.FLOW_DASHBOARD.concat('SET_FLOW_ID'),
  SET_FLOW_UUID: STRINGS.FLOW_DASHBOARD.concat('SET_FLOW_UUID'),
};

export const FIELD_SUGGESTION = {
  STARTED: STRINGS.FIELD_SUGGESTION.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.FIELD_SUGGESTION.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.FIELD_SUGGESTION.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.FIELD_SUGGESTION.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.FIELD_SUGGESTION.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.FIELD_SUGGESTION.concat(STRINGS.CLEAR),
};
export const FIELD_VISIBILITY = {
  ADD_FIELD: STRINGS.FIELD_VISIBILITY.concat(API_STATUS.STARTED),
  REMOVE_FIELD: STRINGS.FIELD_VISIBILITY.concat(API_STATUS.SUCCESS),
  CLEAR_LIST: STRINGS.FIELD_VISIBILITY.concat(STRINGS.CLEAR),
};
export const CATEGORY_LIST = {
  LIST_DATA: STRINGS.CATEGORY_LIST.concat(API_STATUS.SUCCESS),
  STARTED: STRINGS.CATEGORY_LIST.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.CATEGORY_LIST.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.CATEGORY_LIST.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.CATEGORY_LIST.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.CATEGORY_LIST.concat(STRINGS.DATA_CHANGE),
  POST_CANCEL: STRINGS.CATEGORY_LIST.concat(STRINGS.POST_CANCEL),
  CLEAR: STRINGS.CATEGORY_LIST.concat(STRINGS.CLEAR),
  UPDATE: STRINGS.CATEGORY_LIST.concat(STRINGS.UPDATE),
  ADD: STRINGS.CATEGORY_LIST.concat(STRINGS.ADD_CATEGORY_TEXT),
  TOGGLE_VISIBLE: 'TOGGLE_VISIBLE',
  PAGE_DETAILS: STRINGS.CATEGORY_LIST.concat(STRINGS.PAGE_CHANGE),
  PAGE_LOAD: STRINGS.CATEGORY_LIST.concat(STRINGS.PAGE_LOAD),
  CLEAR_DATA: STRINGS.CATEGORY_LIST.concat(STRINGS.INSTANCE_CLEAR),
  ROW_CHANGE: STRINGS.CATEGORY_LIST.concat(STRINGS.ROW_COUNT_CHANGE),
};

export const NAVBAR = {
  TOGGLE: 'TOGGLE',
  TOGGLE_CLOSE: 'TOGGLE_CLOSE',
  COMMON_HEADER_CHANGE: 'COMMON_HEADER_CHANGE',
  DATA_CHANGE: 'DATA_CHANGE',
};

export const SEARCH_RESULT = {
  SEARCH_TEXT: STRINGS.SEARCH_RESULTS.concat(STRINGS.SET_SEARCH),
  SEARCH_FLOW_SUCCESS: STRINGS.SEARCH_RESULTS.concat(
    STRINGS.FLOW_LIST,
  ),
  SEARCH_DATALIST_SUCCESS: STRINGS.SEARCH_RESULTS.concat(STRINGS.DATALIST_LIST),
  SEARCH_TASK_SUCCESS: STRINGS.SEARCH_RESULTS.concat(STRINGS.TASK_LIST),
  SEARCH_CLEAR: STRINGS.SEARCH_RESULTS.concat(STRINGS.CLEAR),
  SEARCH_TASK_STARTED: STRINGS.SEARCH_RESULTS.concat(STRINGS.TASK_SEARCH_START),
  SEARCH_FLOW_STARTED: STRINGS.SEARCH_RESULTS.concat(
    STRINGS.FLOW_SEARCH_START,
  ),
  SEARCH_DATALIST_STARTED: STRINGS.SEARCH_RESULTS.concat(
    STRINGS.DATALIST_SEARCH_START,
  ),
  SEARCH_TASK_FAILURE: STRINGS.SEARCH_RESULTS.concat(STRINGS.TASK_SEARCH_FAIL),
  SEARCH_FLOW_FAILURE: STRINGS.SEARCH_RESULTS.concat(
    STRINGS.FLOW_SEARCH_FAIL,
  ),
  SEARCH_DATALIST_FAILURE: STRINGS.SEARCH_RESULTS.concat(
    STRINGS.DATALIST_SEARCH_FAIL,
  ),
  SEARCH_GLOBAL_DATA: STRINGS.SEARCH_RESULTS.concat(STRINGS.SAVED_SEARCH),
};

export const ACCOUNT_SIGNUP_MODULE = {
  ACCOUNT_SIGNUP_STARTED: STRINGS.ACCOUNT_SIGNUP_MODULE.concat(
    STRINGS.ACCOUNT_STARTED,
  ),
  ACCOUNT_SIGNUP_SUCCESS: STRINGS.ACCOUNT_SIGNUP_MODULE.concat(
    STRINGS.ACCOUNT_SUCCESS,
  ),
  ACCOUNT_SIGNUP_FAILURE: STRINGS.ACCOUNT_SIGNUP_MODULE.concat(
    STRINGS.ACCOUNT_FAILURE,
  ),
  ACCOUNT_SIGNUP_CHANGE: STRINGS.ACCOUNT_SIGNUP_MODULE.concat(
    STRINGS.ACCOUNT_SET_CHANGE,
  ),
  ACCOUNT_SIGNUP_CLEAR: STRINGS.ACCOUNT_SIGNUP_MODULE.concat(STRINGS.CLEAR),
};

export const BILLING_MODULE = {
  EDIT_CHANGE: STRINGS.BILLING_MODULE.concat(STRINGS.CHANGE_EDIT),
  PAYMENT_DATA_STARTED: STRINGS.BILLING_MODULE.concat(
    STRINGS.PAYMENT_DATA_STARTED,
  ),
  SUBSCRIPTION_DATA_STARTED: STRINGS.BILLING_MODULE.concat(
    'SUBSCRIPTION_DATA_STARTED',
  ),
  PAYMENT_DATA_SUCCESS: STRINGS.BILLING_MODULE.concat(
    STRINGS.PAYMENT_DATA_SUCCESS,
  ),
  UPDATED_PAYMENT_DATA_SUCCESS: STRINGS.BILLING_MODULE.concat(
    STRINGS.UPDATED_PAYMENT_DATA_SUCCESS,
  ),
  SUBSCRIPTION_DATA_SUCESS: STRINGS.BILLING_MODULE.concat(
    STRINGS.SUBSCRIPTION_DATA_SUCESS,
  ),

  SUBSCRIPTION_DATA_FAILER: STRINGS.BILLING_MODULE.concat(
    STRINGS.SUBSCRIPTION_DATA_FAILER,
  ),

  PAYMENT_DATA_FAILURE: STRINGS.BILLING_MODULE.concat(
    STRINGS.PAYMENT_DATA_FAILURE,
  ),
  UPDATED_PAYMENT_DATA_FAILURE: STRINGS.BILLING_MODULE.concat(
    STRINGS.UPDATED_PAYMENT_DATA_FAILURE,
  ),
  APICALL_SUCESS: STRINGS.BILLING_MODULE.concat(API_STATUS.SUCCESS),
  CUSTOMIZED_PAYMENT_DATA: STRINGS.BILLING_MODULE.concat(
    STRINGS.CUSTOMIZED_PAYMENT_DATA,
  ),
  CUSTOMIZED_SUBSCRIPTION_DATA: STRINGS.BILLING_MODULE.concat(
    ' CUSTOMIZED_SUBSCRIPTION_DATA',
  ),
  CUSTOMIZED_PAYMENT_PROFILE_DATA: STRINGS.BILLING_MODULE.concat(
    STRINGS.CUSTOMIZED_PAYMENT_PROFILE_DATA,
  ),
  MEMBER_SEARCH_VALUE: STRINGS.BILLING_MODULE.concat(
    STRINGS.MEMBER_SEARCH_VALUE,
  ),
  SELECTED_USER_DATA: STRINGS.BILLING_MODULE.concat(STRINGS.SELECTED_USER_DATA),
  ADD_MEMBER_DATA: STRINGS.BILLING_MODULE.concat(STRINGS.ADD_MEMBER_DATA),
  SET_PAYMENT_DETAILS: STRINGS.BILLING_MODULE.concat(STRINGS.SET_STATE),
  SET_PAYMENT_SPECIFIC_DATA: STRINGS.BILLING_MODULE.concat(
    STRINGS.STATE_CHANGE,
  ),
  SET_BILLING_LOADING_STATUS: STRINGS.BILLING_MODULE.concat(
    STRINGS.LOADING_STATUS,
  ),
  UPDATE_INVOICE_DATA: STRINGS.BILLING_MODULE.concat(
    STRINGS.UPDATE_INVOICE_DATA,
  ),
  BILLING_MODULE_PAGE_CHANGE: STRINGS.BILLING_MODULE.concat(
    STRINGS.BILLING_MODULE_PAGE_CHANGE,
  ),
  GET_ALL_INVOICE_STARTED: STRINGS.BILLING_MODULE.concat(
    STRINGS.GET_ALL_INVOICE_STARTED,
  ),
  GET_ALL_SUBSCRIPTION_LIST: STRINGS.BILLING_MODULE.concat(
    STRINGS.GET_ALL_SUBS_SUCCESS,
  ),
  SAVE_PAYMENT_SETSTATE: STRINGS.BILLING_MODULE.concat(
    STRINGS.SAVE_PAYMENT_SETSTATE,
  ),
  CHANGE_PAYMENT_SCREEN: STRINGS.BILLING_MODULE.concat(
    STRINGS.CHANGE_PAY_SCREEN,
  ),
  SET_PAYMENT_METHOD_STATE_CHANGE: STRINGS.BILLING_MODULE.concat(
    STRINGS.SET_PAYMENT_METHOD_STATE_CHANGE,
  ),
  CLEAR_SET_PAYPROFILE: STRINGS.BILLING_MODULE.concat(
    STRINGS.CLEAR_SET_PAYPROFILE,
  ),
  SET_PAYMENT_REDIRECT_SCREEN: STRINGS.BILLING_MODULE.concat(
    STRINGS.BILLING_REDIRECT,
  ),
};

export const USAGE_DASHBOARD = {
  FLOW_LIST_STARTED: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.FLOW_LIST_STARTED,
  ),
  TASK_FLOW_LIST_STARTED: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.TASK_FLOW_LIST_STARTED,
  ),
  USER_TASK_LIST_STARTED: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.USER_TASK_LIST_STARTED,
  ),
  USAGE_SUMMARY_STARTED: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.USAGE_SUMMARY_STARTED,
  ),
  USERS_SUMMARY_STARTED: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.USERS_SUMMARY_STARTED,
  ),

  FLOW_LIST_SUCCESS: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.FLOW_LIST_SUCCESS,
  ),
  TASK_FLOW_LIST_SUCCESS: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.TASK_FLOW_LIST_SUCCESS,
  ),
  USER_TASK_LIST_SUCCESS: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.USER_TASK_LIST_SUCCESS,
  ),
  USAGE_SUMMARY_SUCCESS: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.USAGE_SUMMARY_SUCCESS,
  ),
  USERS_SUMMARY_SUCCESS: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.USERS_SUMMARY_SUCCESS,
  ),

  FLOW_LIST_FAILURE: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.FLOW_LIST_FAILURE,
  ),
  TASK_FLOW_LIST_FAILURE: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.TASK_FLOW_LIST_FAILURE,
  ),
  USER_TASK_LIST_FAILURE: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.USER_TASK_LIST_FAILURE,
  ),
  USAGE_SUMMARY_FAILURE: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.USAGE_SUMMARY_FAILURE,
  ),
  USERS_SUMMARY_FAILURE: STRINGS.USAGE_DASHBOARD.concat(
    STRINGS.USERS_SUMMARY_FAILURE,
  ),

  CANCEL: STRINGS.USAGE_DASHBOARD.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.USAGE_DASHBOARD.concat(STRINGS.DATA_CHANGE),
  POST_CANCEL: STRINGS.USAGE_DASHBOARD.concat(STRINGS.POST_CANCEL),
  CLEAR: STRINGS.USAGE_DASHBOARD.concat(STRINGS.CLEAR),
  UPDATE: STRINGS.USAGE_DASHBOARD.concat(STRINGS.UPDATE),
};

export const ADMIN_ACCOUNT_LIST = {
  LIST_DATA: STRINGS.ADMIN_ACCOUNT_LIST.concat(API_STATUS.SUCCESS),
  STARTED: STRINGS.ADMIN_ACCOUNT_LIST.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.ADMIN_ACCOUNT_LIST.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.ADMIN_ACCOUNT_LIST.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.ADMIN_ACCOUNT_LIST.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.ADMIN_ACCOUNT_LIST.concat(STRINGS.DATA_CHANGE),
  POST_CANCEL: STRINGS.ADMIN_ACCOUNT_LIST.concat(STRINGS.POST_CANCEL),
  CLEAR: STRINGS.ADMIN_ACCOUNT_LIST.concat(STRINGS.CLEAR),
  UPDATE: STRINGS.ADMIN_ACCOUNT_LIST.concat(STRINGS.UPDATE),
  ADD: STRINGS.ADMIN_ACCOUNT_LIST.concat(STRINGS.ADD_ADMIN_ACCOUNT_TEXT),
  TOGGLE_VISIBLE: 'TOGGLE_VISIBLE',
  PAGE_DETAILS: STRINGS.ADMIN_ACCOUNT_LIST.concat(STRINGS.PAGE_CHANGE),
  PAGE_LOAD: STRINGS.ADMIN_ACCOUNT_LIST.concat(STRINGS.PAGE_LOAD),
  CLEAR_DATA: STRINGS.ADMIN_ACCOUNT_LIST.concat(STRINGS.INSTANCE_CLEAR),
  ROW_CHANGE: STRINGS.ADMIN_ACCOUNT_LIST.concat(STRINGS.ROW_COUNT_CHANGE),
  ACCOUNT_SEARCH_VALUE_CHANGE: STRINGS.ADMIN_ACCOUNT_LIST.concat(
    STRINGS.ACCOUNT_SEARCH_VALUE_CHANGE,
  ),
};

export const ADMIN_ACCOUNT_DETAILS = {
  STARTED: STRINGS.ADMIN_ACCOUNT_DETAILS.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.ADMIN_ACCOUNT_DETAILS.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.ADMIN_ACCOUNT_DETAILS.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.ADMIN_ACCOUNT_DETAILS.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.ADMIN_ACCOUNT_DETAILS.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.ADMIN_ACCOUNT_DETAILS.concat(STRINGS.CLEAR),
  ACCOUNT_CUSTOMISED_DATA: STRINGS.ADMIN_ACCOUNT_DETAILS.concat(
    STRINGS.ACCOUNT_CUSTOMISED_DATA,
  ),
  USAGE_SUMMARY_STARTED: STRINGS.ADMIN_ACCOUNT_USAGE_SUMMARY.concat(
    API_STATUS.STARTED,
  ),
  USAGE_SUMMARY_SUCCESS: STRINGS.ADMIN_ACCOUNT_USAGE_SUMMARY.concat(
    API_STATUS.SUCCESS,
  ),
  USAGE_SUMMARY_FAILURE: STRINGS.ADMIN_ACCOUNT_USAGE_SUMMARY.concat(
    API_STATUS.FAILURE,
  ),
  USAGE_SUMMARY_CLEAR: STRINGS.ADMIN_ACCOUNT_USAGE_SUMMARY.concat(
    STRINGS.CLEAR,
  ),
};

export const FORMULA_BUILDER_ACTION_CONSTANTS = {
  FORMULA_BUILDER_DATA_CHANGE: STRINGS.FORMULA_BUILDER.concat(
    STRINGS.DATA_CHANGE,
  ),
  CLEAR_FORMULA: STRINGS.FORMULA_BUILDER.concat(STRINGS.CLEAR),
  EXTERNAL_FIELDS_SUCCESS: STRINGS.FORMULA_BUILDER.concat(
    EXTERNAL_FIELD_VALUES_CONSTANTS.SUCCESS,
  ),
};

export const ADMIN_ACCOUNT_SUMMARY = {
  STARTED: STRINGS.ADMIN_ACCOUNT_SUMMARY.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.ADMIN_ACCOUNT_SUMMARY.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.ADMIN_ACCOUNT_SUMMARY.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.ADMIN_ACCOUNT_SUMMARY.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.ADMIN_ACCOUNT_SUMMARY.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.ADMIN_ACCOUNT_SUMMARY.concat(STRINGS.CLEAR),
};

export const ADMIN_ACCOUNT_SUMMARY_ACTION_PER_SESSION = {
  STARTED: STRINGS.ADMIN_ACCOUNT_SUMMARY_ACTION_PER_SESSION.concat(
    API_STATUS.STARTED,
  ),
  STOP: STRINGS.ADMIN_ACCOUNT_SUMMARY_ACTION_PER_SESSION.concat(
    API_STATUS.STOP,
  ),
  DATA_CHANGE: STRINGS.ADMIN_ACCOUNT_SUMMARY_ACTION_PER_SESSION.concat(
    STRINGS.DATA_CHANGE,
  ),
};

export const ADMIN_ACCOUNT_SUMMARY_SESSION_COUNT = {
  STARTED: STRINGS.ADMIN_ACCOUNT_SUMMARY_SESSION_COUNT.concat(
    API_STATUS.STARTED,
  ),
  STOP: STRINGS.ADMIN_ACCOUNT_SUMMARY_SESSION_COUNT.concat(API_STATUS.STOP),
  DATA_CHANGE: STRINGS.ADMIN_ACCOUNT_SUMMARY_SESSION_COUNT.concat(
    STRINGS.DATA_CHANGE,
  ),
};

export const ADMIN_ACCOUNT_SUMMARY_ACTIVE_USER_COUNT = {
  STARTED: STRINGS.ADMIN_ACCOUNT_SUMMARY_ACTIVE_USER_COUNT.concat(
    API_STATUS.STARTED,
  ),
  STOP: STRINGS.ADMIN_ACCOUNT_SUMMARY_ACTIVE_USER_COUNT.concat(API_STATUS.STOP),
  DATA_CHANGE: STRINGS.ADMIN_ACCOUNT_SUMMARY_ACTIVE_USER_COUNT.concat(
    STRINGS.DATA_CHANGE,
  ),
};

export const ADMIN_ACCOUNT_SUMMARY_RETENTION_RATE = {
  STARTED: STRINGS.ADMIN_ACCOUNT_SUMMARY_RETENTION_RATE.concat(
    API_STATUS.STARTED,
  ),
  STOP: STRINGS.ADMIN_ACCOUNT_SUMMARY_RETENTION_RATE.concat(API_STATUS.STOP),
  DATA_CHANGE: STRINGS.ADMIN_ACCOUNT_SUMMARY_RETENTION_RATE.concat(
    STRINGS.DATA_CHANGE,
  ),
};

export const EDIT_FLOW_ACTIONS = Object.freeze({
  FLOW_DATA_UPDATE: 'EDIT_FLOW_DATA_UPDATE',
  STEP_INFO_TOGGLE: 'FLOW_STEP_INFO_TOGGLE',
  RESET_STATE: 'EDIT_FLOW_RESET_STATE',
  STATE_DATA_UPDATE: 'EDIT_FLOW_STATE_UPDATE',
  BATCH_DATA_UPDATE: 'BATCH_DATA_UPDATE',
  GET_FLOW_DATA_SUCCESS: 'GET_FLOW_DATA_SUCCESS',
  SAVE_FLOW_SUCCESS: 'SAVE_FLOW_SUCCESS_ACTION',
  FLOW_SET_SECTION: 'EDIT_FLOW_SET_SECTION',
  DEFAULT_VALUE_SAVE_RULE: 'EDIT_DEFAULT_VALUE_SAVE_RULE',
  FLOW_SET_FIELD_LIST: 'EDIT_FLOW_SET_FIELD_LIST',
  FLOW_SET_FIELD_LIST_VALIDATION:
    'EDIT_FLOW_SET_FIELD_LIST_VALIDATION',
  FLOW_SET_ENTIRE_FIELD: 'EDIT_FLOW_SET_ENTIRE_FIELD',
  FLOW_SET_FIELD: 'EDIT_FLOW_SET_FIELD',
  FLOW_DEFAULT_RULE_VALUE: 'FLOW_DEFAULT_RULE_VALUE',
  SET_VISIBILITY_DATA: 'SET_VISIBILITY_DATA',
  FLOW_OPEN_CONFIG: 'FLOW_OPEN_CONFIG',
  FLOW_SET_STEP: 'FLOW_SET_STEP',
  REMOVE_FLOW_DROPDOWN: 'REMOVE_FLOW_DROPDOWN',
  SAVE_RULE: 'EDIT_FLOW_SAVE_RULE',
  UPDATE_NEW_STEP_NAME: 'EDIT_FLOW_UPDATE_NEW_STEP_NAME',
  UPDATE_SINGLE_ACTION_NEXT_STEP_RULE: 'EDIT_FLOW_UPDATE_SINGLE_ACTION_NEXT_STEP_RULE',
  UPDATE_SINGLE_ASSIGNEE_RULE: 'EDIT_FLOW_UPDATE_SINGLE_ASSIGNEE_RULE',
  RESET_PROMPT_DATA: 'RESET_PROMPT_DATA',
  UPDATE_POLICY_CONDITION: 'UPDATE_POLICY_CONDITION',
});
// Download Window
export const DOWNLOAD_WINDOW = {
  STARTED: STRINGS.DOWNLOAD_WINDOW.concat(API_STATUS.STARTED),
  STOP: STRINGS.DOWNLOAD_WINDOW.concat(API_STATUS.STOP),
  SUCCESS: STRINGS.DOWNLOAD_WINDOW.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.DOWNLOAD_WINDOW.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.DOWNLOAD_WINDOW.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.DOWNLOAD_WINDOW.concat(STRINGS.DATA_CHANGE),
  CLEAR: STRINGS.DOWNLOAD_WINDOW.concat(STRINGS.CLEAR),
};

export const URL_VERIFY_API = {
  STARTED: 'URL_VERIFY_API_STARTED',
  SUCCESS: 'URL_VERIFY_API_SUCCESS',
  FAILURE: 'URL_VERIFY_API_FAILURE',
};

export const INTEGRATION_ACTIONS = Object.freeze({
  INTEGRATION_DATA_UPDATE: 'INTEGRATION_DATA_UPDATE',
  DB_CONNECTOR_DATA_UPADTE: 'DB_CONNECTOR_DATA_UPDATE',
});

export const WELCOME_INSIGHTS = {
  ON_DATA_CHANGE: STRINGS.WELCOME_INSIGHTS.concat(STRINGS.DATA_CHANGE),
  STARTED: STRINGS.WELCOME_INSIGHTS.concat(API_STATUS.STARTED),
  STOP: STRINGS.WELCOME_INSIGHTS.concat(API_STATUS.STOP),
  CLEAR: STRINGS.WELCOME_INSIGHTS.concat(STRINGS.CLEAR),
};

export const WEBPAGE_EMBED_WHITELIST = {
  STARTED: STRINGS.WEBPAGE_EMBED_WHITELIST.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.WEBPAGE_EMBED_WHITELIST.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.WEBPAGE_EMBED_WHITELIST.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.WEBPAGE_EMBED_WHITELIST.concat(API_STATUS.CANCEL),
  DATA_CHANGE: STRINGS.WEBPAGE_EMBED_WHITELIST.concat(STRINGS.DATA_CHANGE),
};

export const MFA_DETAILS = {
  STARTED: STRINGS.MFA.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.MFA.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.MFA.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.MFA.concat(API_STATUS.CANCEL),
  UPDATED: STRINGS.MFA.concat(STRINGS.UPDATE),
  INVALID_OTP: STRINGS.MFA.concat(STRINGS.INVALID_OTP),
};

export const INFORMATION_WIDGET = {
  INFORMATION_WIDGET_DATA_CHANGE: 'INFORMATION_WIDGET_DATA_CHANGE',
};

export const ML_MODELS_LIST = {
  STARTED: STRINGS.ML_MODEL.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.ML_MODEL.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.ML_MODEL.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.ML_MODEL.concat(API_STATUS.CANCEL),
  UPDATED: STRINGS.ML_MODEL.concat(STRINGS.UPDATE),
};

export const ML_MODEL_DETAIL = {
  STARTED: STRINGS.ML_MODEL.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.ML_MODEL.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.ML_MODEL.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.ML_MODEL.concat(API_STATUS.CANCEL),
  UPDATED: STRINGS.ML_MODEL.concat(STRINGS.UPDATE),
};

export const ML_MODEL_FLOW_LIST = {
  STARTED: STRINGS.ML_MODEL_FLOW_LIST.concat(API_STATUS.STARTED),
  SUCCESS: STRINGS.ML_MODEL_FLOW_LIST.concat(API_STATUS.SUCCESS),
  FAILURE: STRINGS.ML_MODEL_FLOW_LIST.concat(API_STATUS.FAILURE),
  CANCEL: STRINGS.ML_MODEL_FLOW_LIST.concat(API_STATUS.CANCEL),
  UPDATED: STRINGS.ML_MODEL_FLOW_LIST.concat(STRINGS.UPDATE),
};

export default ACTION_CONSTANTS;
