// import { store } from '../../../Store';
import { ADMIN_SETTINGS_CONSTANT } from '../AdminSettings.constant';
// import { FORM_POPOVER_STATUS } from '../../../utils/Constants';

// let O_S_STRINGS =
//   store.getState().LocalizationReducer.languageSettings.strings.ADMIN_SETTINGS
//     .OTHER_SETTINGS;

export const getOtherSettingsFormStrings = () => {
  return {
    SECURITY_DETAILS: {
      ID: 'security_details',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.TITLE,
    },
    SESSION_TIMEOUT: {
      ID: 'session_timeout',
      TITLE: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.SESSION_TIMEOUT_TITLE,
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.SESSION_TIMEOUT_LABEL,
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.SESSION_TIMEOUT_PLACEHOLDER,
      SUFFIX: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.SESSION_TIMEOUT_SUFFIX,
    },
    MOBILE_APP_SESSION_TIMEOUT: {
      ID: 'mobile_session_timeout',
      TITLE: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MOBILE_APP_SESSION_TIMEOUT_TITLE,
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MOBILE_APP_SESSION_TIMEOUT_LABEL,
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MOBILE_APP_SESSION_TIMEOUT_PLACEHOLDER,
      SUFFIX: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MOBILE_APP_SESSION_TIMEOUT_SUFFIX,
    },
    USER_AUTHENTICATION_POLICIES: {
      TITLE: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.USER_AUTHENTICATION_POLICIES_TITLE,
    },
    STAY_LOGGED_IN: {
      ID: 'remember_me_days',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.STAY_LOGGED_IN_LABEL,
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.STAY_LOGGED_IN_PLACEHOLDER,
      SUFFIX: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.STAY_LOGGED_IN_SUFFIX,
      CHECKBOX_ID: 'is_remember_me_enabled',
    },
    STAY_LOGGED_IN_CB: [{ label: 'Enable', value: 1 }],
    PASSWORD_AGE: {
      ID: 'password_expiry_days',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.PASSWORD_AGE_LABEL,
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.PASSWORD_AGE_PLACEHOLDER,
      SUFFIX: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.PASSWORD_AGE_SUFFIX,
      CHECKBOX_ID: 'is_password_expiry_enabled',
    },
    PASSWORD_AGE_CB: [{ label: 'Enable', value: 1 }],
    MFA_CHECKBOX_ID: 'is_mfa_enabled',
    ENABLE_MFA_TO_USER_CB: [{ label: 'Enable', value: 1 }],
    MFA_SETTINGS: {
      ADD_TEAM_ID: 'add_teams',
      TITLE: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_SETTINGS_TITLE,
      DESCRIPTION: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_SETTINGS_DESCRIPTION,
      ENABLE_MFA_TO_USERS: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_ENABLE_TO_USERS,
      DISABLED_TEXT: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_DISABLED_TEXT,
      ENABLED_TEXT: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_ENABLED_TEXT,
      ALLOWED_MFA_METHODS: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_ALLOWED_MFA_METHODS,
      ALLOWED_MFA_METHODS_VALIDATION_TEXT: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_ALLOWED_MFA_METHODS_VALIDATION_TEXT,
      TOTP_USING_AUTHENTICATOR_APP: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_TOTP_USING_AUTHENTICATOR_APP,
      EMAIL_OTP: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_EMAIL_OTP,
      MAXIMUM_INCORRECT_CODE_ATTEMPTS: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_MAXIMUM_INCORRECT_CODE_ATTEMPTS,
      MAXIMUM_IDLE_TIME: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_MAXIMUM_IDLE_TIME,
      SELECT_TEAMS_TEXT: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_SELECT_TEAMS,
      ADD_TEAM_PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_TEAM_PLACEHOLDER,
      MFA_CONFIRMATION_MODAL: {
        MAIN_CONTENT: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_CONFIRMATION_MODAL.MAIN_CONTENT,
        FIRST_LIST: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_CONFIRMATION_MODAL.FIRST_LIST,
        SECOND_LINE: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_CONFIRMATION_MODAL.SECOND_LINE,
        CANCEL_BUTTON: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_CONFIRMATION_MODAL.CANCEL_BUTTON,
        DELETE_BUTTON: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MFA_CONFIRMATION_MODAL.DELETE_BUTTON,
      },
    },
    DOCUMENT_SETTINGS: {
      ID: 'document_settings',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.DOCUMENT_SETTINGS,
    },
    MAXIMUM_FILE_SIZE: {
      ID: 'maximum_file_size',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MAXIMUM_FILE_SIZE_LABEL,
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.FILE_SIZE_PLACEHOLDER,
      SUFFIX: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.MAXIMUM_FILE_SIZE_SUFFIX,
    },
    // DOCUMENT_EXPIRY_TIME: {
    //   ID: 'doc_expiry_time',
    //   LABEL: O_S_STRINGS.DOCUMENT_EXPIRY_TIME_LABEL,
    //   PLACEHOLDER: 'Eg: 30',
    //   SUFFIX: 'Days',
    // },
    ALLOWED_EXTENSIONS: {
      ID: 'allowed_extensions',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.ALLOWED_EXTENSIONS_LABEL,
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.ALLOWED_EXTENSIONS_PLACEHOLDER,
      DESCRIPTION: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.ALLOWED_EXTENSIONS_DESCRIPTION,
    },
    CURRENCY_SETTINGS: {
      ID: 'currency_settings',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.CURRENCY_SETTINGS_LABEL,
    },
    ALLOWED_CURRENCY_TYPES: {
      ID: 'allowed_currency_types',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.ALLOWED_CURRENCY_TYPES_LABEL,
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.ALLOWED_CURRENCY_TYPES_PLACEHOLDER,
      DESCRIPTION: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.ALLOWED_CURRENCY_TYPES_DESCRIPTION,
      NO_DATA_FOUND_LABEL: 'No Data found in Allowed Currency Types',
    },
    DEFAULT_CURRENCY: {
      ID: 'default_currency_type',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.DEFAULT_CURRENCY_LABEL,
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.DEFAULT_CURRENCY_PLACEHOLDER,
    },
    PHONE_NUMBER_SETTINGS: {
      ID: 'phone_number_settings',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.PHONE_NUMBER_SETTINGS_LABEL,
    },
    WEBPAGE_EMBED_SETTING: {
      ID: 'webpage_embed_settings',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.WEBPAGE_EMBED_SETTING_LABEL,
    },
    DEFAULT_COUNTRY_CODE_SETTING: {
      ID: 'default_country_code',
      LABEL: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.DEFAULT_COUNTRY_CODE_LABEL,
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.SECURITY_SETTINGS.DEFAULT_COUNTRY_CODE_PLACEHOLDER,
    },
    SAVE: { LABEL: ADMIN_SETTINGS_CONSTANT.COMMON_STRINGS.SAVE },
    CANCEL: { LABEL: ADMIN_SETTINGS_CONSTANT.COMMON_STRINGS.CANCEL },
  };
};

export const OTHER_SETTINGS_FORM = getOtherSettingsFormStrings();

export const OTHER_SETTINGS_LABELS = {
  [OTHER_SETTINGS_FORM.SESSION_TIMEOUT.ID]:
    OTHER_SETTINGS_FORM.SESSION_TIMEOUT.LABEL,
  [OTHER_SETTINGS_FORM.MOBILE_APP_SESSION_TIMEOUT.ID]:
    OTHER_SETTINGS_FORM.MOBILE_APP_SESSION_TIMEOUT.LABEL,
  [OTHER_SETTINGS_FORM.STAY_LOGGED_IN.ID]:
    OTHER_SETTINGS_FORM.STAY_LOGGED_IN.LABEL,
  [OTHER_SETTINGS_FORM.PASSWORD_AGE.ID]: OTHER_SETTINGS_FORM.PASSWORD_AGE.LABEL,
  [OTHER_SETTINGS_FORM.MAXIMUM_FILE_SIZE.ID]:
    OTHER_SETTINGS_FORM.MAXIMUM_FILE_SIZE.LABEL,
  [OTHER_SETTINGS_FORM.ALLOWED_EXTENSIONS.ID]:
    OTHER_SETTINGS_FORM.ALLOWED_EXTENSIONS.LABEL,
};

// store.subscribe(() => {
//   O_S_STRINGS =
//     store.getState().LocalizationReducer.languageSettings.strings.ADMIN_SETTINGS
//       .OTHER_SETTINGS;
//   // OTHER_SETTINGS_FORM = getOtherSettingsFormStrings();
// });

// export default OTHER_SETTINGS_FORM;
