import { RESPONSE_FIELD_KEYS, RESPONSE_VALIDATION_KEYS } from '../../../../../../utils/constants/form/form.constant';
import { FIELD_TYPES } from '../../FieldConfiguration.strings';

export const getFieldGuidanceConfigurationValidationData = (fieldData) => {
    return {
        [RESPONSE_FIELD_KEYS.EDIT_REFERENCE_NAME]: fieldData?.[RESPONSE_FIELD_KEYS.EDIT_REFERENCE_NAME] || false,
        [RESPONSE_FIELD_KEYS.TEMPORARY_REFERENCE_NAME]: fieldData?.[RESPONSE_FIELD_KEYS.TEMPORARY_REFERENCE_NAME],
        [RESPONSE_FIELD_KEYS.HELPER_TOOLTIP]: fieldData?.[RESPONSE_FIELD_KEYS.HELPER_TOOLTIP],
        [RESPONSE_FIELD_KEYS.PLACEHOLDER]: fieldData?.[RESPONSE_FIELD_KEYS.PLACEHOLDER],
        [RESPONSE_FIELD_KEYS.INSTRUCTION]: fieldData?.[RESPONSE_FIELD_KEYS.INSTRUCTION],
        [RESPONSE_VALIDATION_KEYS[FIELD_TYPES.PARAGRAPH].SHOW_ELLIPSIS]: fieldData?.[RESPONSE_VALIDATION_KEYS[FIELD_TYPES.PARAGRAPH].SHOW_ELLIPSIS],
        [RESPONSE_VALIDATION_KEYS[FIELD_TYPES.PARAGRAPH].ELLIPSIS_LENGTH]: fieldData?.[RESPONSE_VALIDATION_KEYS[FIELD_TYPES.PARAGRAPH].ELLIPSIS_LENGTH],
      };
};

export const PLACEHOLDER_APPLICABLE_FIELD_TYPES = [
  FIELD_TYPES.SINGLE_LINE,
  FIELD_TYPES.NUMBER,
  FIELD_TYPES.PARAGRAPH,
  FIELD_TYPES.DROPDOWN,
  FIELD_TYPES.CURRENCY,
  FIELD_TYPES.CUSTOM_LOOKUP_DROPDOWN,
  FIELD_TYPES.PHONE_NUMBER,
  FIELD_TYPES.EMAIL,
];
