import { translateFunction } from 'utils/jsUtility';
import { ADD_MEMBER_BASIC_DETAILS_FORM } from './add_member/add_member_basic_details/AddMemberBasicDetails.strings';
import { OTHER_DETAILS_FORM } from './add_member/other_details/OtherDetails.strings';

export const ADD_OR_INVITE_MEMBERS_TAB_INDEX = {
  ADD_MEMBER: 1,
  INVITE_MEMBER: 2,
};

export const ADD_OR_INVITE_MEMBERS_TABS = [
  {
    TEXT: 'Add User',
    INDEX: ADD_OR_INVITE_MEMBERS_TAB_INDEX.ADD_MEMBER,
  },
  {
    TEXT: 'Invite User',
    INDEX: ADD_OR_INVITE_MEMBERS_TAB_INDEX.INVITE_MEMBER,
  },
];

export const ADD_OR_INVITE_MEMBERS = {
  TITLE: 'Add or Invite Users',
};

export const USER_NAME_UNIQUE_CONSTRAIN = 5;

export const ADD_OR_INVITE_MEMBERS_LABELS = (t = translateFunction) => {
 return {
  [ADD_MEMBER_BASIC_DETAILS_FORM.FIRST_NAME.ID]: ADD_MEMBER_BASIC_DETAILS_FORM.FIRST_NAME.LABEL,
  [ADD_MEMBER_BASIC_DETAILS_FORM.LAST_NAME.ID]: ADD_MEMBER_BASIC_DETAILS_FORM.LAST_NAME.LABEL,
  [ADD_MEMBER_BASIC_DETAILS_FORM.USER_NAME.ID]: t(ADD_MEMBER_BASIC_DETAILS_FORM.USER_NAME.LABEL),
  [ADD_MEMBER_BASIC_DETAILS_FORM.EMAIL.ID]: t(ADD_MEMBER_BASIC_DETAILS_FORM.EMAIL.LABEL),
  [ADD_MEMBER_BASIC_DETAILS_FORM.USER_TYPE_RADIO().ID]: ADD_MEMBER_BASIC_DETAILS_FORM.USER_TYPE_RADIO().LABEL,
  [OTHER_DETAILS_FORM.ROLE.ID]: OTHER_DETAILS_FORM.ROLE.LABEL,
  [OTHER_DETAILS_FORM.BUSSINESS_UNIT.ID]: OTHER_DETAILS_FORM.BUSSINESS_UNIT.LABEL,
  [OTHER_DETAILS_FORM.PHONE_NUMBER.ID]: OTHER_DETAILS_FORM.PHONE_NUMBER.ID,
  [OTHER_DETAILS_FORM.MOBILE_NUMBER.ID]: OTHER_DETAILS_FORM.MOBILE_NUMBER.LABEL,
  [OTHER_DETAILS_FORM.ADD_ROLE.ID]: OTHER_DETAILS_FORM.ADD_ROLE.LABEL,
  [OTHER_DETAILS_FORM.ADD_BUSINESS_UIT.ID]: OTHER_DETAILS_FORM.ADD_BUSINESS_UIT.LABEL,
 };
};

export const ADD_OR_INVITE_USERS_ERROR = (t) => {
  return {
    TRIAL_LIMIT: t('admin_settings.user_management.trial_expired_error'),
    LIMIT_EXCEED: t('admin_settings.user_management.limit_exceeded_error'),
  };
};
