// Country model:
// [
//    Country name,
//    Regions,
//    iso2 code,
//    International dial code,
//    Format (if available),
//    Order (if >1 country with same dial code),
//    Area codes (if >1 country with same dial code)
// ]
//
// Regions:
// ['america', 'europe', 'asia', 'oceania', 'africa']
//
// Sub-regions:
// ['north-america', 'south-america', 'central-america', 'carribean',
//  'eu-union', 'ex-ussr', 'ex-yugos', 'baltic', 'middle-east', 'north-africa']

const countryCodeList = [
  { countryName: 'Afghanistan', countryCode: 'af', countryCodeId: '+93' },
  { countryName: 'Albania', countryCode: 'al', countryCodeId: '+355' },
  { countryName: 'Algeria', countryCode: 'dz', countryCodeId: '+213' },
  { countryName: 'American Samoa', countryCode: 'as', countryCodeId: '+1684' },
  { countryName: 'Andorra', countryCode: 'ad', countryCodeId: '+376' },
  { countryName: 'Angola', countryCode: 'ao', countryCodeId: '+244' },
  { countryName: 'Anguilla', countryCode: 'ai', countryCodeId: '+1264' },
  {
    countryName: 'Antigua and Barbuda',
    countryCode: 'ag',
    countryCodeId: '+1268',
  },
  { countryName: 'Argentina', countryCode: 'ar', countryCodeId: '+54' },
  { countryName: 'Armenia', countryCode: 'am', countryCodeId: '+374' },
  { countryName: 'Aruba', countryCode: 'aw', countryCodeId: '+297' },
  { countryName: 'Australia', countryCode: 'au', countryCodeId: '+61' },
  { countryName: 'Austria', countryCode: 'at', countryCodeId: '+43' },
  { countryName: 'Azerbaijan', countryCode: 'az', countryCodeId: '+994' },
  { countryName: 'Bahamas', countryCode: 'bs', countryCodeId: '+1242' },
  { countryName: 'Bahrain', countryCode: 'bh', countryCodeId: '+973' },
  { countryName: 'Bangladesh', countryCode: 'bd', countryCodeId: '+880' },
  { countryName: 'Barbados', countryCode: 'bb', countryCodeId: '+1246' },
  { countryName: 'Belarus', countryCode: 'by', countryCodeId: '+375' },
  { countryName: 'Belgium', countryCode: 'be', countryCodeId: '+32' },
  { countryName: 'Belize', countryCode: 'bz', countryCodeId: '+501' },
  { countryName: 'Benin', countryCode: 'bj', countryCodeId: '+229' },
  { countryName: 'Bermuda', countryCode: 'bm', countryCodeId: '+1441' },
  { countryName: 'Bhutan', countryCode: 'bt', countryCodeId: '+975' },
  { countryName: 'Bolivia', countryCode: 'bo', countryCodeId: '+591' },
  {
    countryName: 'Bosnia and Herzegovina',
    countryCode: 'ba',
    countryCodeId: '+387',
  },
  { countryName: 'Botswana', countryCode: 'bw', countryCodeId: '+267' },
  { countryName: 'Brazil', countryCode: 'br', countryCodeId: '+55' },
  {
    countryName: 'British Indian Ocean Territory',
    countryCode: 'io',
    countryCodeId: '+246',
  },
  {
    countryName: 'British Virgin Islands',
    countryCode: 'vg',
    countryCodeId: '+1284',
  },
  { countryName: 'Brunei', countryCode: 'bn', countryCodeId: '+673' },
  { countryName: 'Bulgaria', countryCode: 'bg', countryCodeId: '+359' },
  { countryName: 'Burkina Faso', countryCode: 'bf', countryCodeId: '+226' },
  { countryName: 'Burundi', countryCode: 'bi', countryCodeId: '+257' },
  { countryName: 'Cambodia', countryCode: 'kh', countryCodeId: '+855' },
  { countryName: 'Cameroon', countryCode: 'cm', countryCodeId: '+237' },
  { countryName: 'Canada', countryCode: 'ca', countryCodeId: '+1' },
  { countryName: 'Cape Verde', countryCode: 'cv', countryCodeId: '+238' },
  {
    countryName: 'Caribbean Netherlands',
    countryCode: 'bq',
    countryCodeId: '+599',
  },
  { countryName: 'Cayman Islands', countryCode: 'ky', countryCodeId: '+1345' },
  {
    countryName: 'Central African Republic',
    countryCode: 'cf',
    countryCodeId: '+236',
  },
  { countryName: 'Chad', countryCode: 'td', countryCodeId: '+235' },
  { countryName: 'Chile', countryCode: 'cl', countryCodeId: '+56' },
  { countryName: 'China', countryCode: 'cn', countryCodeId: '+86' },
  { countryName: 'Colombia', countryCode: 'co', countryCodeId: '+57' },
  { countryName: 'Comoros', countryCode: 'km', countryCodeId: '+269' },
  { countryName: 'Congo', countryCode: 'cd', countryCodeId: '+243' },
  { countryName: 'Congo', countryCode: 'cg', countryCodeId: '+242' },
  { countryName: 'Cook Islands', countryCode: 'ck', countryCodeId: '+682' },
  { countryName: 'Costa Rica', countryCode: 'cr', countryCodeId: '+506' },
  { countryName: 'Côte d’Ivoire', countryCode: 'ci', countryCodeId: '+225' },
  { countryName: 'Croatia', countryCode: 'hr', countryCodeId: '+385' },
  { countryName: 'Cuba', countryCode: 'cu', countryCodeId: '+53' },
  { countryName: 'Curaçao', countryCode: 'cw', countryCodeId: '+599' },
  { countryName: 'Cyprus', countryCode: 'cy', countryCodeId: '+357' },
  { countryName: 'Czech Republic', countryCode: 'cz', countryCodeId: '+420' },
  { countryName: 'Denmark', countryCode: 'dk', countryCodeId: '+45' },
  { countryName: 'Djibouti', countryCode: 'dj', countryCodeId: '+253' },
  { countryName: 'Dominica', countryCode: 'dm', countryCodeId: '+1767' },
  { countryName: 'Dominican Republic', countryCode: 'do', countryCodeId: '+1' },
  { countryName: 'Ecuador', countryCode: 'ec', countryCodeId: '+593' },
  { countryName: 'Egypt', countryCode: 'eg', countryCodeId: '+20' },
  { countryName: 'El Salvador', countryCode: 'sv', countryCodeId: '+503' },
  { countryName: 'Equatorial Guinea', countryCode: 'gq', countryCodeId: '+240' },
  { countryName: 'Eritrea', countryCode: 'er', countryCodeId: '+291' },
  { countryName: 'Estonia', countryCode: 'ee', countryCodeId: '+372' },
  { countryName: 'Ethiopia', countryCode: 'et', countryCodeId: '+251' },
  { countryName: 'Falkland Islands', countryCode: 'fk', countryCodeId: '+500' },
  { countryName: 'Faroe Islands', countryCode: 'fo', countryCodeId: '+298' },
  { countryName: 'Fiji', countryCode: 'fj', countryCodeId: '+679' },
  { countryName: 'Finland', countryCode: 'fi', countryCodeId: '+358' },
  { countryName: 'France', countryCode: 'fr', countryCodeId: '+33' },
  { countryName: 'French Guiana', countryCode: 'gf', countryCodeId: '+594' },
  { countryName: 'French Polynesia', countryCode: 'pf', countryCodeId: '+689' },
  { countryName: 'Gabon', countryCode: 'ga', countryCodeId: '+241' },
  { countryName: 'Gambia', countryCode: 'gm', countryCodeId: '+220' },
  { countryName: 'Georgia', countryCode: 'ge', countryCodeId: '+995' },
  { countryName: 'Germany', countryCode: 'de', countryCodeId: '+49' },
  { countryName: 'Ghana', countryCode: 'gh', countryCodeId: '+233' },
  { countryName: 'Gibraltar', countryCode: 'gi', countryCodeId: '+350' },
  { countryName: 'Greece', countryCode: 'gr', countryCodeId: '+30' },
  { countryName: 'Greenland', countryCode: 'gl', countryCodeId: '+299' },
  { countryName: 'Grenada', countryCode: 'gd', countryCodeId: '+1473' },
  { countryName: 'Guadeloupe', countryCode: 'gp', countryCodeId: '+590' },
  { countryName: 'Guam', countryCode: 'gu', countryCodeId: '+1671' },
  { countryName: 'Guatemala', countryCode: 'gt', countryCodeId: '+502' },
  { countryName: 'Guinea', countryCode: 'gn', countryCodeId: '+224' },
  { countryName: 'Guinea-Bissau', countryCode: 'gw', countryCodeId: '+245' },
  { countryName: 'Guyana', countryCode: 'gy', countryCodeId: '+592' },
  { countryName: 'Haiti', countryCode: 'ht', countryCodeId: '+509' },
  { countryName: 'Honduras', countryCode: 'hn', countryCodeId: '+504' },
  { countryName: 'Hong Kong', countryCode: 'hk', countryCodeId: '+852' },
  { countryName: 'Hungary', countryCode: 'hu', countryCodeId: '+36' },
  { countryName: 'Iceland', countryCode: 'is', countryCodeId: '+354' },
  { countryName: 'India', countryCode: 'in', countryCodeId: '+91' },
  { countryName: 'Indonesia', countryCode: 'id', countryCodeId: '+62' },
  { countryName: 'Iran', countryCode: 'ir', countryCodeId: '+98' },
  { countryName: 'Iraq', countryCode: 'iq', countryCodeId: '+964' },
  { countryName: 'Ireland', countryCode: 'ie', countryCodeId: '+353' },
  { countryName: 'Israel', countryCode: 'il', countryCodeId: '+972' },
  { countryName: 'Italy', countryCode: 'it', countryCodeId: '+39' },
  { countryName: 'Jamaica', countryCode: 'jm', countryCodeId: '+1876' },
  { countryName: 'Japan', countryCode: 'jp', countryCodeId: '+81' },
  { countryName: 'Jordan', countryCode: 'jo', countryCodeId: '+962' },
  { countryName: 'Kazakhstan', countryCode: 'kz', countryCodeId: '+7' },
  { countryName: 'Kenya', countryCode: 'ke', countryCodeId: '+254' },
  { countryName: 'Kiribati', countryCode: 'ki', countryCodeId: '+686' },
  { countryName: 'Kosovo', countryCode: 'xk', countryCodeId: '+383' },
  { countryName: 'Kuwait', countryCode: 'kw', countryCodeId: '+965' },
  { countryName: 'Kyrgyzstan', countryCode: 'kg', countryCodeId: '+996' },
  { countryName: 'Laos', countryCode: 'la', countryCodeId: '+856' },
  { countryName: 'Latvia', countryCode: 'lv', countryCodeId: '+371' },
  { countryName: 'Lebanon', countryCode: 'lb', countryCodeId: '+961' },
  { countryName: 'Lesotho', countryCode: 'ls', countryCodeId: '+266' },
  { countryName: 'Liberia', countryCode: 'lr', countryCodeId: '+231' },
  { countryName: 'Libya', countryCode: 'ly', countryCodeId: '+218' },
  { countryName: 'Liechtenstein', countryCode: 'li', countryCodeId: '+423' },
  { countryName: 'Lithuania', countryCode: 'lt', countryCodeId: '+370' },
  { countryName: 'Luxembourg', countryCode: 'lu', countryCodeId: '+352' },
  { countryName: 'Macau', countryCode: 'mo', countryCodeId: '+853' },
  { countryName: 'Macedonia', countryCode: 'mk', countryCodeId: '+389' },
  { countryName: 'Madagascar', countryCode: 'mg', countryCodeId: '+261' },
  { countryName: 'Malawi', countryCode: 'mw', countryCodeId: '+265' },
  { countryName: 'Malaysia', countryCode: 'my', countryCodeId: '+60' },
  { countryName: 'Maldives', countryCode: 'mv', countryCodeId: '+960' },
  { countryName: 'Mali', countryCode: 'ml', countryCodeId: '+223' },
  { countryName: 'Malta', countryCode: 'mt', countryCodeId: '+356' },
  { countryName: 'Marshall Islands', countryCode: 'mh', countryCodeId: '+692' },
  { countryName: 'Martinique', countryCode: 'mq', countryCodeId: '+596' },
  { countryName: 'Mauritania', countryCode: 'mr', countryCodeId: '+222' },
  { countryName: 'Mauritius', countryCode: 'mu', countryCodeId: '+230' },
  { countryName: 'Mexico', countryCode: 'mx', countryCodeId: '+52' },
  { countryName: 'Micronesia', countryCode: 'fm', countryCodeId: '+691' },
  { countryName: 'Moldova', countryCode: 'md', countryCodeId: '+373' },
  { countryName: 'Monaco', countryCode: 'mc', countryCodeId: '+377' },
  { countryName: 'Mongolia', countryCode: 'mn', countryCodeId: '+976' },
  { countryName: 'Montenegro', countryCode: 'me', countryCodeId: '+382' },
  { countryName: 'Montserrat', countryCode: 'ms', countryCodeId: '+1664' },
  { countryName: 'Morocco', countryCode: 'ma', countryCodeId: '+212' },
  { countryName: 'Mozambique', countryCode: 'mz', countryCodeId: '+258' },
  { countryName: 'Myanmar', countryCode: 'mm', countryCodeId: '+95' },
  { countryName: 'Namibia', countryCode: 'na', countryCodeId: '+264' },
  { countryName: 'Nauru', countryCode: 'nr', countryCodeId: '+674' },
  { countryName: 'Nepal', countryCode: 'np', countryCodeId: '+977' },
  { countryName: 'Netherlands', countryCode: 'nl', countryCodeId: '+31' },
  { countryName: 'New Caledonia', countryCode: 'nc', countryCodeId: '+687' },
  { countryName: 'New Zealand', countryCode: 'nz', countryCodeId: '+64' },
  { countryName: 'Nicaragua', countryCode: 'ni', countryCodeId: '+505' },
  { countryName: 'Niger', countryCode: 'ne', countryCodeId: '+227' },
  { countryName: 'Nigeria', countryCode: 'ng', countryCodeId: '+234' },
  { countryName: 'Niue', countryCode: 'nu', countryCodeId: '+683' },
  { countryName: 'Norfolk Island', countryCode: 'nf', countryCodeId: '+672' },
  { countryName: 'North Korea', countryCode: 'kp', countryCodeId: '+850' },
  {
    countryName: 'Northern Mariana Islands',
    countryCode: 'mp',
    countryCodeId: '+1670',
  },
  { countryName: 'Norway', countryCode: 'no', countryCodeId: '+47' },
  { countryName: 'Oman', countryCode: 'om', countryCodeId: '+968' },
  { countryName: 'Pakistan', countryCode: 'pk', countryCodeId: '+92' },
  { countryName: 'Palau', countryCode: 'pw', countryCodeId: '+680' },
  { countryName: 'Palestine', countryCode: 'ps', countryCodeId: '+970' },
  { countryName: 'Panama', countryCode: 'pa', countryCodeId: '+507' },
  { countryName: 'Papua New Guinea', countryCode: 'pg', countryCodeId: '+675' },
  { countryName: 'Paraguay', countryCode: 'py', countryCodeId: '+595' },
  { countryName: 'Peru', countryCode: 'pe', countryCodeId: '+51' },
  { countryName: 'Philippines', countryCode: 'ph', countryCodeId: '+63' },
  { countryName: 'Poland', countryCode: 'pl', countryCodeId: '+48' },
  { countryName: 'Portugal', countryCode: 'pt', countryCodeId: '+351' },
  { countryName: 'Puerto Rico', countryCode: 'pr', countryCodeId: '+1' },
  { countryName: 'Qatar', countryCode: 'qa', countryCodeId: '+974' },
  { countryName: 'Réunion', countryCode: 're', countryCodeId: '+262' },
  { countryName: 'Romania', countryCode: 'ro', countryCodeId: '+40' },
  { countryName: 'Russia', countryCode: 'ru', countryCodeId: '+7' },
  { countryName: 'Rwanda', countryCode: 'rw', countryCodeId: '+250' },
  { countryName: 'Saint Barthélemy', countryCode: 'bl', countryCodeId: '+590' },
  { countryName: 'Saint Helena', countryCode: 'sh', countryCodeId: '+290' },
  {
    countryName: 'Saint Kitts and Nevis',
    countryCode: 'kn',
    countryCodeId: '+1869',
  },
  { countryName: 'Saint Lucia', countryCode: 'lc', countryCodeId: '+1758' },
  { countryName: 'Saint Martin', countryCode: 'mf', countryCodeId: '+590' },
  {
    countryName: 'Saint Pierre and Miquelon',
    countryCode: 'pm',
    countryCodeId: '+508',
  },
  {
    countryName: 'Saint Vincent and the Grenadines',
    countryCode: 'vc',
    countryCodeId: '+1784',
  },
  { countryName: 'Samoa', countryCode: 'ws', countryCodeId: '+685' },
  { countryName: 'San Marino', countryCode: 'sm', countryCodeId: '+378' },
  {
    countryName: 'São Tomé and Príncipe',
    countryCode: 'st',
    countryCodeId: '+239',
  },
  { countryName: 'Saudi Arabia', countryCode: 'sa', countryCodeId: '+966' },
  { countryName: 'Senegal', countryCode: 'sn', countryCodeId: '+221' },
  { countryName: 'Serbia', countryCode: 'rs', countryCodeId: '+381' },
  { countryName: 'Seychelles', countryCode: 'sc', countryCodeId: '+248' },
  { countryName: 'Sierra Leone', countryCode: 'sl', countryCodeId: '+232' },
  { countryName: 'Singapore', countryCode: 'sg', countryCodeId: '+65' },
  { countryName: 'Sint Maarten', countryCode: 'sx', countryCodeId: '+1721' },
  { countryName: 'Slovakia', countryCode: 'sk', countryCodeId: '+421' },
  { countryName: 'Slovenia', countryCode: 'si', countryCodeId: '+386' },
  { countryName: 'Solomon Islands', countryCode: 'sb', countryCodeId: '+677' },
  { countryName: 'Somalia', countryCode: 'so', countryCodeId: '+252' },
  { countryName: 'South Africa', countryCode: 'za', countryCodeId: '+27' },
  { countryName: 'South Korea', countryCode: 'kr', countryCodeId: '+82' },
  { countryName: 'South Sudan', countryCode: 'ss', countryCodeId: '+211' },
  { countryName: 'Spain', countryCode: 'es', countryCodeId: '+34' },
  { countryName: 'Sri Lanka', countryCode: 'lk', countryCodeId: '+94' },
  { countryName: 'Sudan', countryCode: 'sd', countryCodeId: '+249' },
  { countryName: 'Suriname', countryCode: 'sr', countryCodeId: '+597' },
  { countryName: 'Swaziland', countryCode: 'sz', countryCodeId: '+268' },
  { countryName: 'Sweden', countryCode: 'se', countryCodeId: '+46' },
  { countryName: 'Switzerland', countryCode: 'ch', countryCodeId: '+41' },
  { countryName: 'Syria', countryCode: 'sy', countryCodeId: '+963' },
  { countryName: 'Taiwan', countryCode: 'tw', countryCodeId: '+886' },
  { countryName: 'Tajikistan', countryCode: 'tj', countryCodeId: '+992' },
  { countryName: 'Tanzania', countryCode: 'tz', countryCodeId: '+255' },
  { countryName: 'Thailand', countryCode: 'th', countryCodeId: '+66' },
  { countryName: 'Timor-Leste', countryCode: 'tl', countryCodeId: '+670' },
  { countryName: 'Togo', countryCode: 'tg', countryCodeId: '+228' },
  { countryName: 'Tokelau', countryCode: 'tk', countryCodeId: '+690' },
  { countryName: 'Tonga', countryCode: 'to', countryCodeId: '+676' },
  {
    countryName: 'Trinidad and Tobago',
    countryCode: 'tt',
    countryCodeId: '+1868',
  },
  { countryName: 'Tunisia', countryCode: 'tn', countryCodeId: '+216' },
  { countryName: 'Turkey', countryCode: 'tr', countryCodeId: '+90' },
  { countryName: 'Turkmenistan', countryCode: 'tm', countryCodeId: '+993' },
  {
    countryName: 'Turks and Caicos Islands',
    countryCode: 'tc',
    countryCodeId: '+1649',
  },
  { countryName: 'Tuvalu', countryCode: 'tv', countryCodeId: '+688' },
  {
    countryName: 'U.S. Virgin Islands',
    countryCode: 'vi',
    countryCodeId: '+1340',
  },
  { countryName: 'Uganda', countryCode: 'ug', countryCodeId: '+256' },
  { countryName: 'Ukraine', countryCode: 'ua', countryCodeId: '+380' },
  {
    countryName: 'United Arab Emirates',
    countryCode: 'ae',
    countryCodeId: '+971',
  },
  { countryName: 'United Kingdom', countryCode: 'gb', countryCodeId: '+44' },
  { countryName: 'United States', countryCode: 'us', countryCodeId: '+1' },
  { countryName: 'Uruguay', countryCode: 'uy', countryCodeId: '+598' },
  { countryName: 'Uzbekistan', countryCode: 'uz', countryCodeId: '+998' },
  { countryName: 'Vanuatu', countryCode: 'vu', countryCodeId: '+678' },
  { countryName: 'Vatican City', countryCode: 'va', countryCodeId: '+39' },
  { countryName: 'Venezuela', countryCode: 've', countryCodeId: '+58' },
  { countryName: 'Vietnam', countryCode: 'vn', countryCodeId: '+84' },
  { countryName: 'Wallis and Futuna', countryCode: 'wf', countryCodeId: '+681' },
  { countryName: 'Yemen', countryCode: 'ye', countryCodeId: '+967' },
  { countryName: 'Zambia', countryCode: 'zm', countryCodeId: '+260' },
  { countryName: 'Zimbabwe', countryCode: 'zw', countryCodeId: '+263' },
];

export default countryCodeList;
