const ACTION_HISTORY_ACTION = {
    COMPLETED: 'task_content.action_history.completed',
    INITIATED: 'task_content.action_history.initiated',
    REJECTED: 'task_content.action_history.rejected',
    REASSIGNED: 'task_content.action_history.reassigned',
    REASSIGNED_TO: 'task_content.action_history.reassigned_to',
    REASSIGNED_REASON: 'task_content.action_history.reassigned_reason',
    CANCELED: 'task_content.action_history.canceled',
    CREATED: 'task_content.action_history.created',
    TRIGGERED: 'task_content.action_history.triggered',
    WITH_TASK_ACTION: 'task_content.action_history.with_task_action',
    SNOOZED: 'task_content.action_history.snoozed',
    UNTIL: 'task_content.action_history.until',
    AT: 'task_content.action_history.at',
    TASK_UPDATE: 'task_content.action_history.task_update',
    ASSIGN_BACK: 'task_content.action_history.assign_back',
    FLOW_FLOW_FOR: 'task_content.action_history.flow_flow_for',
    TO_THE_ORIGINAL_ASSIGNEES: 'task_content.action_history.to_the_original_assignees',
    COMPLETED_LABEL: 'task_content.action_history.completed_label',
    COMPLETED_INTEGRATION_TASK: 'task_content.action_history.completed_integration_task',
    FAILED_INTEGRATION_TASK: 'task_content.action_history.failed_integration_task',
    SUCCESSFULLY_COMPLETED_INTEGRATION: 'task_content.action_history.successfully_completed_integration',
    COMPLETED_ML_INTEGRATION_TASK: 'task_content.action_history.completed_ml_integration_task',
    FAILED_ML_INTEGRATION_TASK: 'task_content.action_history.failed_ml_integration_task',
    SUCCESSFULLY_COMPLETED_ML_INTEGRATION: 'task_content.action_history.successfully_completed_ml_integration',
};
export default ACTION_HISTORY_ACTION;
