import { TASK_CONTENT_STRINGS } from 'containers/landing_page/LandingPage.strings';
import { translateFunction } from 'utils/jsUtility';

export const RESPONDANTS_SUMMARY_STRINGS = {
  TITLE: (t = translateFunction) => {
    return {
  TITLE: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.TITLE),
    };
  },
  TABLE_TITLES: (t = translateFunction) => {
    return {
    ASSIGNEE_NAME: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.TABLE_HEADERS.ASSIGNEE_NAME),
    IS_RESPONDED: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.TABLE_HEADERS.IS_RESPONDED),
    RESPONDED_ON: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.TABLE_HEADERS.RESPONDED_ON),
    YES: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.YES),
    NO: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.NO),
    NO_TASK_CANCELLED: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.NO_TASK_CANCELLED),
    NUDGE: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.NUDGE),
    };
  },
  NUDGE_ALL_BUTTON: (t = translateFunction) => {
    return {
    LABEL: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.NUDGE_ALL),
    };
  },
  NUDGE_BUTTON: (t = translateFunction) => {
    return {
    LABEL: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.NUDGE),
    };
  },
  DOWNLOAD_BUTTON: (t = translateFunction) => {
    return {
    LABEL: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.DOWNLOAD),
    };
  },
  ARIA_LABEL: (t = translateFunction) => {
    return {
    NUDGE: t(TASK_CONTENT_STRINGS.TASK_INFO.DATA_SUMMARY.NUDGE),
    };
  },
};

export default RESPONDANTS_SUMMARY_STRINGS;
