export const SIDE_NAV_BAR = {
    TASK: 'Task',
    OPEN_TASK: 'side_nav_bar.nav_task',
    AWAITING_RESPONSE: 'Awaiting Response',
    REPORTEE_TASK: "Reportee's Task",
    TASK_METRICS: 'Task Metrics',
    FLOW: 'side_nav_bar.nav_my_flows',
    ALL_FLOWS: 'All Flows',
    MY_FLOWS: 'side_nav_bar.nav_my_flows',
    MY_DATA_LIST: 'side_nav_bar.nav_my_data_list',
    COLLABORATION: 'Collaboration',
    PEOPLE: 'side_nav_bar.nav_people',
    TEAMS: 'side_nav_bar.nav_teams',
    START: 'Start',
    HOME: 'side_nav_bar.nav_home',
    MENU_LABEL: 'side_nav_bar.menu_label',
    ADMIN_SETTINGS: 'side_nav_bar.nav_admin_settings',
    BILLING: 'side_nav_bar.nav_billing',
    ADMIN_ACCOUNTS: 'super_admin.common_header.accounts',
    INTEGRATION: 'side_nav_bar.nav_integration',
    ADD_INTEGRATION: 'integration.integration_strings.add_integration.add_integration',
    REPORTS: 'side_nav_bar.nav_reports',
    CREATE: 'side_nav_bar.nav_create',
    APPLICATIONS: 'landing_page.main_header.common_header.applications',
    ML_MODELS: 'side_nav_bar.nav_mlmodels',
};
export const SIDE_NAV_BAR_DROP_DOWN = {
    CREATE_TASK: 'side_nav_bar.create_task',
    CREATE_FLOW: 'side_nav_bar.create_flow',
    CREATE_DATA_LIST: 'side_nav_bar.create_datalist',
};

export const SIDE_NAV_BAR_SPA = {
    TASK: 'Tarea',
    OPEN_TASK: 'Abre Tareas',
    AWAITING_RESPONSE: 'Espera de la respuesta',
    REPORTEE_TASK: 'Reportée de tarea',
    TASK_METRICS: 'Tarea Metrics',
    FLOW: 'Procedimiento',
    ALL_FLOWS: 'Todos los procedimientos',
    MY_FLOWS: 'Mi',
    ProcedimientosCOLLABORATION: 'Colaboración',
    PEOPLE: 'Personas',
    TEAMS: 'Equipos',
    START: 'Comienzo',
    HOME: 'Casa',
    ADMIN_SETTINGS: 'Configuración de administrador',
    BILLING: 'facturación',
};

export const MAIN_HEADER_SEARCHBAR = {
    PLACEHOLDER: 'landing_page.main_header.common_header.searchbar_placeholder',
    ID: 'global_search',
};
export const LANDING_PAGE_TOPICS = {
    TASK: 'landing_page.main_header.common_header.my_task',
    FLOW: 'landing_page.main_header.common_header.flows',
    DATALIST: 'landing_page.main_header.common_header.datalist',
    INTEGRATION: 'landing_page.main_header.common_header.integration',
    MORE: 'landing_page.main_header.common_header.more',
    HOME: 'landing_page.main_header.common_header.home',
    TEAMS: 'landing_page.main_header.common_header.teams',
    TASKS: 'landing_page.main_header.common_header.tasks',
    UPGRADE_NOW: 'landing_page.main_header.common_header.upgrade_now',
    TRAIL_EXPIRES: 'landing_page.main_header.common_header.trial_expires',
    DAYS: 'landing_page.main_header.common_header.days',
    USERS: 'landing_page.main_header.common_header.users',
    ADMIN_SETTINGS: 'landing_page.main_header.common_header.admin_settings',
    BILLING: 'landing_page.main_header.common_header.billing',
    CREATE_TASK: 'landing_page.main_header.common_header.create_task',
    CREATE_FLOW: 'landing_page.main_header.common_header.create_flow',
    CREATE_DATALIST: 'landing_page.main_header.common_header.create_datalist',
    CREATE_TEAM: 'landing_page.main_header.common_header.create_team',
    APPLICATIONS: 'landing_page.main_header.common_header.applications',
    REPORTS: 'landing_page.main_header.common_header.reports',
    ML_MODELS: 'landing_page.main_header.common_header.ml_models',
};
export const LANDING_PAGE_NO_FLOW_FOUND = {
    LABEL: 'landing_page.all_flow.flow_string.no_flow_found',
};
