import { translateFunction } from 'utils/jsUtility';
import { DROPDOWN_CONSTANTS } from '../../../utils/strings/CommonStrings';
import { store } from '../../../Store';
import { FORM_POPOVER_STATUS } from '../../../utils/Constants';
import { getYearDropDown } from '../../../utils/dateUtils';
import { ADMIN_SETTINGS_CONSTANT } from '../AdminSettings.constant';

let L_C_STRINGS = store.getState().LocalizationReducer.languageSettings.strings.ADMIN_SETTINGS
  .LANGUAGE_AND_CALENDAR_SETTINGS;

export const getLanguageSettingsStrings = () => {
  return {
    LANGUAGAE_DETAILS: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.SUB_TITLE,
    TIME_DAY_DETAILS: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.TIME_DAY_DETAILS.TITLE,
    HOLIDAYS: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.HOLIDAYS,
    RESTRICT_LANGUAGE_LOCALE_UPDATE: 'allow_update_language_locale',
    RESTRICT_TIMEZONE_UPDATE: 'allow_update_timezone',
    L_DROPDOWN: {
      LABEL: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.LANGUAGE.LABEL,
      ID: 'acc_language',
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.LANGUAGE.PLACEHOLDER,
    },
    LOCALE_DROPDOWN: {
      LABEL: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.LOCALE.LABEL,
      ID: 'acc_locale',
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.LOCALE.PLACEHOLDER,
    },
    TZ_DROPDOWN: {
      LABEL: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.TIME_DAY_DETAILS.TIME_ZONE.LABEL,
      ID: 'acc_timezone',
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.TIME_DAY_DETAILS.TIME_ZONE.PLACEHOLDER,
    },
    WORKING_HOURS_FROM_DROPDOWN: {
      LABEL: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.TIME_DAY_DETAILS.WORKING_HOURS_LABEL,
      ID: 'working_hour_start_time',
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.TIME_DAY_DETAILS.WORKING_HOURS_PLACEHOLDER,
    },
    WORKING_HOURS_TO_DROPDOWN: {
      ID: 'working_hour_end_time',
      PLACEHOLDER: L_C_STRINGS.WORKING_HOURS_TO_DROPDOWN_PLACEHOLDER,
    },
    WORKING_DAYS: {
      LABEL: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.TIME_DAY_DETAILS.WORKING_DAYS_LABEL,
      ID: 'working_days',
    },
    YEAR_DROPDOWN: {
      LABEL: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.HOLIDAYS_YEAR_LABEL,
      ID: 'year',
      PLACEHOLDER: ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.HOLIDAYS_YEAR_PLACEHOLDER,
    },
    SUCCESSFUL_UPDATE: (t = translateFunction) => {
      return {
      title: t(L_C_STRINGS.SUCCESSFUL_UPDATE_TITLE),
      subTitle: t(L_C_STRINGS.SUCCESSFUL_UPDATE_SUBTITLE),
      status: FORM_POPOVER_STATUS.SUCCESS,
      isVisible: true,
      };
    },
    UPDATE_FAILURE: {
      title: L_C_STRINGS.UPDATE_FAILURE_TITLE,
      status: FORM_POPOVER_STATUS.SERVER_ERROR,
      isVisible: true,
    },
    LANGUAGE_LOCALE_CB: (t) => {
      return {
        ID: 'language_locale_cb',
        OPTION_LIST: [{ label: t(ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.LANGUAGE.ALLOW_USER), value: 1 }],
      };
    },
    TIME_ZONE_CB: (t) => {
      return {
      ID: 'timezone_cb',
      OPTION_LIST: [{ label: t(ADMIN_SETTINGS_CONSTANT.LANGUAGE_CALENDAR.TIME_DAY_DETAILS.ALLOW_USER), value: 1 }],
      };
    },
  };
};
export const VALIDATE_SCHEMA = {
  WORK_START_TIME: 'Start Time',
  WORK_END_TIME: 'End time',
};

export const L_C_FORM = getLanguageSettingsStrings();
export const SCHEDULER_FORM = getLanguageSettingsStrings();

export const YEAR_DROPDOWN = getYearDropDown();

export const WORKING_HOURS_FROM_TO_DROPDOWN = [
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '12:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '12:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '01:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '01:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '02:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '02:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '03:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '03:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '04:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '04:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '05:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '05:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '06:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '06:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '07:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '07:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '08:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '08:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '09:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '09:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '10:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '10:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '11:00 AM',
    [DROPDOWN_CONSTANTS.VALUE]: '11:00 AM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '12:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '12:00 PM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '01:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '01:00 PM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '02:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '02:00 PM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '03:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '03:00 PM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '04:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '04:00 PM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '05:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '05:00 PM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '06:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '06:00 PM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '07:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '07:00 PM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '08:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '08:00 PM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '09:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '09:00 PM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '10:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '10:00 PM',
  },
  {
    [DROPDOWN_CONSTANTS.OPTION_TEXT]: '11:00 PM',
    [DROPDOWN_CONSTANTS.VALUE]: '11:00 PM',
  },
];

store.subscribe(() => {
  L_C_STRINGS = store.getState().LocalizationReducer.languageSettings.strings.ADMIN_SETTINGS
    .LANGUAGE_AND_CALENDAR_SETTINGS;
});
