export const FORM_TITLE_COLOR = '#5c5fa8';

export const COLOR_PICKER = {
  PRIMARY: {
    TEXT: 'Primary Color',
    ID: 'primary_color',
  },
  SECONDARY: {
    TEXT: 'Secondary Color',
    ID: 'secondary_color',
  },
  BUTTON: {
    TEXT: 'Button Color',
    ID: 'button_color',
  },
};
export const INPUT_NAME = {
  RADIO_GROUP_NAME: 'user_type',
};
export const INPUT_TYPES = {
  TEXT: 'text',
  NUMBER: 'number',
  PASSWORD: 'password',
  FILE: 'file',
  CHECKBOX: 'checkbox',
  RADIO: 'radio',
  BUTTON: 'button',
};
export const INPUT_PLACEHOLDERS = {
  EMAIL: 'Enter name or email here..',
};
export const BS = {
  TEXT_JUSTIFY: 'text-justify',
  TEXT_CENTER: 'text-center',
  TEXT_LEFT: 'text-left',
  TEXT_RIGHT: 'text-right',
  ABSOLUTE: 'absolute',
  P_ABSOLUTE: 'position-absolute',
  P_FIXED: 'position-fixed',
  P_STICKY: 'position-sticky',
  P_RELATIVE: 'position-relative',
  VISIBLE: 'visible',
  INVISIBLE: 'invisible',
  W100: 'w-100',
  W75: 'w-75',
  W50: 'w-50',
  W30: 'w-30',
  W70: 'w-70',
  W65: 'w-65',
  W_AUTO: 'w-auto',
  H100: 'h-100',
  MB_0: 'mb-0',
  BORDER_0: 'border-0',
  D_FLEX: 'd-flex',
  D_BLOCK: 'd-block',
  D_NONE: 'd-none',
  FLOAT_RIGHT: 'float-right',
  FLOAT_LEFT: 'float-left',
  JC_END: 'justify-content-end',
  JC_BETWEEN: 'justify-content-between',
  JC_CENTER: 'justify-content-center',
  ALIGN_ITEM_CENTER: 'align-items-center',
  JC_START: 'justify-content-start',
  AI_BASELINE: 'align-items-baseline',
  ALIGN_CONTENT_START: 'align-content-start',
  ALIGN_ITEMS_START: 'align-items-start',
  ALIGN_ITEMS_END: 'align-items-end',
  AI_END: 'align-items-end',
  AS_END: 'align-self-end',
  BT_0: 'border-top-0',
  BR_0: 'border-right-0',
  BL_0: 'border-left-0',
  BB_0: 'border-bottom-0',
  CONTAINER_FLUID: 'container-fluid',
  CONTAINER: 'container',
  PL_0: 'pl-0',
  PR_0: 'pr-0',
  PADDING_0: 'p-0',
  MARGIN_0: 'm-0',
  ML_0: 'ml-0',
  MR_0: 'mr-0',
  FLEX_WRAP_WRAP: 'flex-wrap',
  FLEX_WRAP_NO_WRAP: 'flex-nowrap',
  D_FLEX_JUSTIFY_CENTER: 'd-flex justify-content-center',
  D_FLEX_JUSTIFY_END: 'd-flex justify-content-end',
  HOVER: ':hover',
  HIDDEN: 'hidden',
  INHERIT: 'inherit',
  FLEX_ROW: 'flex-row',
  FLEX_COLUMN: 'flex-column',
  FLEX_FLOW_REVERSE: 'flex-row-reverse',
  TEXT_NO_WRAP: 'text-nowrap',
  TEXT_WRAP: 'text-wrap ',
  OVERFLOW_AUTO: 'overflow-auto',
  M_AUTO: 'm-auto',
  MT_AUTO: 'mt-auto',
  MB_AUTO: 'mb-auto',
  ML_AUTO: 'ml-auto',
  MR_AUTO: 'mr-auto',
  MY_AUTO: 'my-auto',
  TABLE_RESPONSIVE: 'table-responsive',
  ALERT: 'alert',
  ALERT_WARNING: 'alert-warning',
};

export const DEFAULT_COLORS_CONSTANTS = {
  PRIMARY: '#485289',
  SECONDARY: '#1f243d',
  BUTTON: '#228bb5',
  PINK: '#f93bca',
  PINK_V2: '#fa2e85',
  GRAY_V1: '#5b6375',
  GRAY_V2: '#353a50',
  GRAY_V3: '#d8dee9',
  BLUE_V39: '#217CF5',
  LIGHT_BLUE: '#e8f2fe',
  BLACK_DEFAULT: '#1A1A1A',
  GRAY_103: '#EFEFEF',
};

export const BS_LAYOUT_COL = {
  ZERO: 0,
  ONE: 1,
  TWO: 2,
  THREE: 3,
  FOUR: 4,
  FIVE: 5,
  SIX: 6,
  SEVEN: 7,
  EIGHT: 8,
  NINE: 9,
  TEN: 10,
  ELEVEN: 11,
  TWELVE: 12,
};

export const TEXT_DIRECTION = {
  RTL: 1,
  LTR: 2,
};

export const COLOR_CONSTANTS = {
  ERROR: '#e62a2a',
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  BLACK_V1: '#1A1A1A',
  GRAY: '#a4adbe',
  BLUE_V7: '#e6f3f9',
  BLUE_V1: '#D8DEE9',
  BLUE_V2: '#E9F2FE',
  GRAY_v2: '#5b6375',
  GRAY_v10: '#eff1f4',
  SKELETON_LOADER_GRAY_COLOR: '#EEEEEE',
  RED_V5: '#f07f7f',
  GREY_10: '#F2F4F7',
  GREY_500: '#344054',
  BLUE_10: '#EBF4FF',
  BLUE_500: '#1A4AC8',
};

export const ARIA_ROLES = {
  ALERT: 'alert',
  APPLICATION: 'application',
  ARTICLE: 'article',
  BANNER: 'banner',
  BUTTON: 'button',
  CAROUSEL: 'carousel',
  CELL: 'cell',
  CHECKBOX: 'checkbox',
  COMBOBOX: 'combobox',
  COMPLEMENTARY: 'complementary',
  CONTENT_INFO: 'contentinfo',
  DIALOG: 'dialog',
  DOCUMENT: 'document',
  FEED: 'feed',
  FIGURE: 'figure',
  FORM: 'form',
  GRID: 'grid',
  GROUP: 'group',
  GRID_CELL: 'gridcell',
  HEADING: 'heading',
  INPUT: 'input',
  IMG: 'img',
  LINK: 'link',
  LIST: 'list',
  LIST_BOX: 'listbox',
  LIST_ITEM: 'listitem',
  MAIN: 'main',
  NAVIGATION: 'navigation',
  RADIO: 'radio',
  REGION: 'region',
  ROW: 'row',
  ROW_GROUP: 'rowgroup',
  SEARCH: 'search',
  SWITCH: 'switch',
  SLIDE: 'slide',
  TAB: 'tab',
  TABLE: 'table',
  TAB_PANEL: 'tabpanel',
  TEXT_BOX: 'textbox',
  TIMER: 'timer',
  PROGRESS_BAR: 'progressbar',
  PRESENTATION: 'presentation',
};

export const PIXEL_CONSTANTS = {
  ZERO_PIXEL: '0px',
  ONE_EIGHT_PIXEL: '180px',
  ONE_TWENTY_PIXEL: '120px',
  FOUR_HUNDRED_PIXEL: '400px',
  FIFTY_PIXEL: '50px',
  TWENTY_FOUR_PIXEL: '24px', // contentPadding
};

export const CSS_STYLES = {
  BLOCK: 'block',
  NONE: 'none',
};

export const SKELETON_LOADER_DIMENSION_CONSTANTS = {
  PX16: 16,
  PX18: 18,
  PX22: 22,
  PX32: 32,
  PX34: 34,
  PX54: 54,
  PX100: 100,
  PX150: 150,
  PERCENTAGE100: '100%',
  PERCENTAGE50: '50%',
};

export const COLOUR_CODES = {
  GRAY_V3: '#1f243d',
  GRAY_V6: '#adb6c7',
  GRAY_V7: '#b8bfc7',
  GRAY_V87: '#959ba3',
  BLACK_V18: '#484D57',
  GREEN_V24: '#ECFDF3',
  RED_V24: '#FEF3F2',
  GRAY_V107: '#F2F4F7',
  GREEN_V27: '#027A48',
  RED_V25: '#B42318',
  BLACK_V20: '#344054',
};
