import i18next from 'i18next';

export const FIELD_VALIDATION = (t = i18next) => {
    return {
        COUNTRY_CODE: t('task_validation_strings.country_code'),
        IS_REQUIRED: t('task_validation_strings.is_required'),
        MUST_BE_ATLEAST: t('task_validation_strings.must_be_atleast'),
        DIGITS_LONG: t('task_validation_strings.digits_long'),
        MUST_BE_LESS_THAN: t('task_validation_strings.must_be_less_than'),
        DIGITS: t('task_validation_strings.digits'),
     };
};

export const USER_PROFILE_DETAILS = {
    _id: '6267f86145883f0012781da0',
    account_id: '6267f86122897e0013511661',
    maximum_file_size: 5,
    allowed_extensions: [
      'gif',
      'tiff',
      'tif',
      'mp4',
      'avi',
      'mpg',
      'mpeg',
      '3gpp',
      'iso',
      'mov',
      'wmv',
      'ogv',
      'ico',
      'jpg',
      'pdf',
      'png',
      'mp3',
      'wav',
      'ogg',
      'opus',
      'jpeg',
    ],
    allowed_currency_types: [
      'JMD',
      'JOD',
      'CAD',
      'INR',
      'JPY',
      'AFN',
      'AUD',
      'USD',
      'AED',
      'ALL',
      'ANG',
      'AMD',
      'AWG',
      'AZN',
      'BAM',
      'BBD',
      'BDT',
      'BIF',
      'CDF',
      'CHE',
      'CHF',
    ],
    default_currency_type: 'JMD',
    default_country_code: '+91',
    is_mfa_enabled: true,
    mfa_details: {
      allowed_mfa_methods: [
        1,
        2,
      ],
      mfa_enforced_teams: [],
    },
};

export const VISIBILITY = {
    visible_sections: {
        '10e0ac75-7a6e-429d-b66c-e657b7c98344': true,
    },
    visible_tables: {},
    visible_fields: {
        field_single: true,
        field_number: true,
        field_paragraph: true,
        field_email: true,
        field_yes_or_no: true,
        field_checkbox: true,
        field_radio: true,
        field_dropdown: true,
        field_CSD: true,
        field_date: true,
        field_date_time: true,
        field_user_selector: true,
        field_data_list_selector: true,
        field_file_upload: true,
        field_phone_number: true,
        field_currency: true,
        field_link: true,
        field_information: true,
    },
};
